(() => {
  'use strict';
  if (window.__Z33_FINAL__) return;
  window.__Z33_FINAL__ = true;

  const URL = 'https://ponhllwbvhtczaphfdgw.supabase.co';
  const KEY = 'sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
  const db = window.supabase.createClient(URL, KEY, { auth:{ persistSession:true, autoRefreshToken:true, detectSessionInUrl:true } });
  const $ = (s,r=document)=>r.querySelector(s);
  const esc = (v)=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money = (v)=>'$'+Number(v||0).toLocaleString('es-MX',{maximumFractionDigits:0});
  const today = ()=>new Date().toISOString().slice(0,10);
  const pad = n=>String(n).padStart(2,'0');
  const time = v=>String(v||'').slice(0,5);
  const date = v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-MX',{day:'2-digit',month:'short'}):'—';
  const fullDate = v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short',year:'numeric'}):'—';
  const addDays=(v,n)=>{const d=new Date(v+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
  const monday=(v)=>{const d=new Date(v+'T12:00:00');const day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));return d.toISOString().slice(0,10)};
  const state={page:'dashboard',anchor:monday(today()),tab:'payments',clients:[],coaches:[],classes:[],reservations:[],payments:[],memberships:[],plans:[],founders:[],expenses:[]};
  const slotsWeek=['05:30','06:30','07:30','08:30','09:30','10:30','11:30','12:30','17:00','18:00','19:00'];
  const slotsSat=['07:00','08:00','09:00','10:00','11:00'];

  const css = `
  :root{--bg:#f6f6f7;--card:#fff;--line:#e8e8ea;--text:#171719;--muted:#78787f;--soft:#f1f1f3;--accent:#d52431;--green:#087a4b;--shadow:0 8px 30px rgba(20,20,24,.05)}
  #z33final{min-height:100vh;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
  #z33final *{box-sizing:border-box}
  .zf-top{height:68px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 22px;gap:14px;position:sticky;top:0;z-index:50}
  .zf-menu{width:38px;height:38px;border:0;border-radius:10px;background:#fff;font-size:20px;display:grid;place-items:center;cursor:pointer}
  .zf-menu:hover{background:var(--soft)}
  .zf-brand{font-size:15px;font-weight:800;letter-spacing:.01em}.zf-brand span{font-weight:500;color:#98989e;margin-left:6px}
  .zf-title{font-size:14px;font-weight:700;color:#55555b;margin-left:8px}.zf-spacer{flex:1}.zf-link{border:1px solid #dedee2;background:#fff;color:#28282c;border-radius:9px;padding:9px 12px;font-size:11px;font-weight:700;cursor:pointer}.zf-link.danger{border-color:#efcdca;color:#b4232e;background:#fff8f7}.zf-status{font-size:11px;background:#eaf8f1;color:#087a4b;border-radius:999px;padding:7px 10px;font-weight:700}
  .zf-main{max-width:1180px;margin:0 auto;padding:30px 26px 60px}.zf-kicker{font-size:10px;letter-spacing:.13em;text-transform:uppercase;font-weight:800;color:#a0a0a6}.zf-h1{font-size:32px;letter-spacing:-.04em;margin:4px 0 4px;font-weight:760}.zf-sub{color:var(--muted);font-size:13px}
  .zf-head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:20px}.zf-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.zf-btn{border:1px solid #dcdce0;background:#fff;border-radius:9px;padding:9px 13px;font-size:11px;font-weight:700;color:#2c2c31;cursor:pointer}.zf-btn:hover{background:#f8f8f9}.zf-btn.primary{background:#1b1b1d;color:#fff;border-color:#1b1b1d}.zf-btn.red{background:var(--accent);color:#fff;border-color:var(--accent)}
  .zf-grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.zf-stat{background:#fff;border:1px solid var(--line);border-radius:14px;padding:17px;box-shadow:var(--shadow)}.zf-stat .n{font-size:27px;font-weight:650;letter-spacing:-.03em}.zf-stat .l{margin-top:6px;font-size:12px;color:var(--muted)}
  .zf-grid2{display:grid;grid-template-columns:1.15fr .85fr;gap:14px;margin-top:14px}.zf-card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px;box-shadow:var(--shadow)}.zf-card h3{font-size:15px;margin:0 0 14px}.zf-list{display:grid;gap:8px}.zf-item{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 12px;border:1px solid #ededee;border-radius:10px;background:#fcfcfc}.zf-item .small{font-size:11px;color:var(--muted);margin-top:3px}.zf-badge{display:inline-flex;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:800}.zf-badge.ok{background:#eaf8f1;color:#087a4b}.zf-badge.warn{background:#fff5dc;color:#916a00}.zf-badge.bad{background:#fdeceb;color:#b4232e}
  .zf-table{background:#fff;border:1px solid var(--line);border-radius:14px;overflow:auto;box-shadow:var(--shadow)}.zf-table table{width:100%;min-width:760px;border-collapse:collapse}.zf-table th{background:#fafafb;color:#86868d;text-transform:uppercase;font-size:9px;letter-spacing:.06em;text-align:left;padding:11px 13px;border-bottom:1px solid var(--line)}.zf-table td{padding:12px 13px;border-bottom:1px solid #f0f0f1;font-size:12px}.zf-table tr:last-child td{border-bottom:0}
  .zf-tabs{display:flex;gap:2px;border-bottom:1px solid var(--line);margin:20px 0 14px}.zf-tab{border:0;background:transparent;padding:11px 13px;font-size:11px;font-weight:750;color:#84848b;border-bottom:2px solid transparent;cursor:pointer}.zf-tab.active{color:#1e1e21;border-color:#1e1e21}
  .zf-search{height:38px;border:1px solid #dcdce0;border-radius:9px;padding:0 11px;font-size:11px;width:min(360px,100%)}
  .zf-drawer-bg{position:fixed;inset:0;background:rgba(0,0,0,.24);z-index:80;display:none}.zf-drawer-bg.show{display:block}.zf-drawer{position:fixed;top:0;right:0;bottom:0;width:min(500px,94vw);background:#fff;z-index:81;padding:22px;overflow:auto;box-shadow:-20px 0 50px rgba(0,0,0,.12)}
  .zf-drawer-head{display:flex;align-items:flex-start;gap:10px}.zf-drawer-head .close{margin-left:auto}.zf-form{display:grid;gap:12px;margin-top:18px}.zf-form label{font-size:10px;font-weight:750;color:#6f6f77}.zf-form input,.zf-form select,.zf-form textarea{width:100%;margin-top:6px;border:1px solid #dbdbe0;border-radius:9px;padding:11px 12px;font-size:12px;background:#fff}.zf-form textarea{min-height:90px}.zf-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}
  .zf-calendar{background:#fff;border:1px solid var(--line);border-radius:14px;overflow:auto;box-shadow:var(--shadow)}.zf-cal-inner{min-width:1050px}.zf-week-head{display:grid;grid-template-columns:58px repeat(7,1fr);background:#fafafb;border-bottom:1px solid var(--line)}.zf-week-head>div{padding:9px 4px;text-align:center;border-left:1px solid #f0f0f1}.zf-week-head small{font-size:8px;text-transform:uppercase;color:#8d8d94}.zf-week-head b{display:block;margin-top:4px;font-size:13px}.zf-cal-body{display:grid;grid-template-columns:58px 1fr}.zf-time-col{height:900px;position:relative}.zf-time-label{position:absolute;right:7px;transform:translateY(-5px);font-size:8px;color:#98989f}.zf-day-cols{display:grid;grid-template-columns:repeat(7,1fr);height:900px}.zf-day{position:relative;border-left:1px solid #f1f1f2}.zf-gridline{position:absolute;left:0;right:0;border-top:1px solid #f5f5f6}.zf-slot{position:absolute;left:6px;right:6px;height:50px;border:1px dashed #e7e7ea;background:#fdfdfd;border-radius:7px;display:flex;align-items:center;justify-content:center;color:#a2a2a8;font-size:9px;cursor:pointer}.zf-slot:hover{background:#fff4f4;border-color:#efb3b7;color:#b3212b}.zf-class{position:absolute;left:5px;right:5px;border:1px solid #e0e0e3;border-left:3px solid #242429;background:#fff;border-radius:8px;padding:6px;cursor:pointer;box-shadow:0 2px 6px rgba(20,20,24,.04)}.zf-class:hover{box-shadow:0 6px 15px rgba(20,20,24,.09)}.zf-class strong{display:block;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.zf-class small{display:block;font-size:8px;color:#888890;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.zf-class.full{border-left-color:var(--accent);background:#fff6f6}
  .zf-drawer-grid{display:grid;gap:10px}.zf-muted{color:#8a8a91;font-size:11px}.zf-empty{padding:32px;text-align:center;color:#909097;border:1px dashed #dedee2;border-radius:10px;background:#fcfcfc}
  .zf-menu-bg{position:fixed;inset:0;background:rgba(0,0,0,.24);z-index:90;display:none}.zf-menu-bg.show{display:block}.zf-menu{position:fixed;left:0;top:0;bottom:0;width:290px;background:#fff;z-index:91;transform:translateX(-100%);transition:transform .18s;box-shadow:15px 0 45px rgba(0,0,0,.12);padding:22px}.zf-menu.show{transform:translateX(0)}.zf-menu-brand{font-size:18px;font-weight:800}.zf-menu-sub{font-size:11px;color:#93939a;margin-top:4px}.zf-nav{display:grid;gap:4px;margin-top:22px}.zf-nav button{height:42px;border:0;background:#fff;border-radius:9px;text-align:left;padding:0 12px;font-size:12px;font-weight:700;color:#616168;cursor:pointer}.zf-nav button:hover,.zf-nav button.active{background:#f3f3f4;color:#1a1a1d}.zf-menu-foot{position:absolute;left:22px;right:22px;bottom:20px;color:#9c9ca2;font-size:9px;line-height:1.45}
  @media(max-width:900px){.zf-grid4,.zf-grid2{grid-template-columns:1fr}.zf-main{padding:22px 14px 70px}.zf-row{grid-template-columns:1fr}.zf-status{display:none}.zf-top{padding:0 14px}}
  `;
  function style(){if($('#z33FinalStyle'))return;const s=document.createElement('style');s.id='z33FinalStyle';s.textContent=css;document.head.appendChild(s)}

  async function load(){
    const [cl,co,classes,res,pay,mem,plans,found,exp]=await Promise.all([
      db.from('profiles').select('*').eq('role','cliente').order('created_at',{ascending:false}),
      db.from('coaches').select('*').order('is_active',{ascending:false}).order('name'),
      db.from('classes').select('*,coaches(name)').gte('class_date',today()).order('class_date').order('start_time'),
      db.from('reservations').select('*,profiles(full_name,email,phone)').order('created_at',{ascending:false}),
      db.from('payments').select('*,profiles(full_name,email),membership_plans(name,is_founder_plan)').order('payment_date',{ascending:false}),
      db.from('memberships').select('*,profiles(full_name,email),membership_plans(name,price,is_founder_plan)').order('created_at',{ascending:false}),
      db.from('membership_plans').select('*').order('sort_order').order('name'),
      db.from('founder_codes').select('*').order('created_at',{ascending:false}),
      db.from('expenses').select('*').order('expense_date',{ascending:false})
    ]);
    state.clients=cl.data||[];state.coaches=co.data||[];state.classes=classes.data||[];state.reservations=res.data||[];state.payments=pay.data||[];state.memberships=mem.data||[];state.plans=plans.data||[];state.founders=found.data||[];state.expenses=exp.data||[];
  }
  const booked=id=>state.reservations.filter(r=>r.class_id===id&&r.status==='reserved').length;

  function shell(){
    document.body.innerHTML=`<div id="z33final"><header class="zf-top"><button class="zf-menu" id="zfOpen">☰</button><div class="zf-brand">ZONA 33 <span>Admin</span></div><div class="zf-title" id="zfTitle">Dashboard</div><div class="zf-spacer"></div><span class="zf-status">Conectado</span><button class="zf-link" onclick="location.href='https://zona33.pages.dev/'">Sitio</button><button class="zf-link danger" id="zfLogout">Salir</button></header><main class="zf-main" id="zfMain"></main><div id="zfMenuBg" class="zf-menu-bg"></div><aside id="zfMenu" class="zf-menu"><div class="zf-menu-brand">ZONA 33</div><div class="zf-menu-sub">Panel administrativo</div><nav class="zf-nav" id="zfNav"></nav><div class="zf-menu-foot">ZONA 33 FUNCTIONAL CLUB<br>Gestión operativa</div></aside><div id="zfDrawerBg" class="zf-drawer-bg"><aside id="zfDrawer" class="zf-drawer"></aside></div></div>`;
    $('#zfOpen').onclick=()=>{$('#zfMenuBg').classList.add('show');$('#zfMenu').classList.add('show')};
    $('#zfMenuBg').onclick=closeMenu;
    $('#zfLogout').onclick=async()=>{await db.auth.signOut();location.reload()};
    drawMenu();
  }
  function closeMenu(){$('#zfMenuBg')?.classList.remove('show');$('#zfMenu')?.classList.remove('show')}
  function drawMenu(){const items=[['dashboard','Dashboard'],['clients','Clientes'],['agenda','Clases / horarios'],['coaches','Coaches'],['finance','Finanzas'],['landing','Editar Landing']];$('#zfNav').innerHTML=items.map(([k,v])=>`<button class="${state.page===k?'active':''}" data-page="${k}">${v}</button>`).join('');document.querySelectorAll('#zfNav button').forEach(b=>b.onclick=()=>{closeMenu();state.page=b.dataset.page;render()})}
  function setTitle(t){$('#zfTitle').textContent=t}

  function dashboard(){
    setTitle('Dashboard');
    const month=today().slice(0,7);const income=state.payments.filter(p=>p.status==='approved'&&String(p.payment_date||'').startsWith(month)).reduce((s,p)=>s+Number(p.amount||0),0);const pending=state.payments.filter(p=>p.status==='pending').reduce((s,p)=>s+Number(p.amount||0),0);const active=state.memberships.filter(m=>m.status==='active'&&m.end_date>=today()).length;const todayClasses=state.classes.filter(c=>c.class_date===today());
    $('#zfMain').innerHTML=`<div class="zf-head"><div><div class="zf-kicker">RESUMEN</div><div class="zf-h1">Dashboard</div><div class="zf-sub">Control general de ZONA 33.</div></div><div class="zf-actions"><button class="zf-btn" onclick="state.page='agenda';render()">Ver agenda</button><button class="zf-btn red" onclick="openPayment()">Registrar pago</button></div></div><div class="zf-grid4"><div class="zf-stat"><div class="n">${money(income)}</div><div class="l">Ingresos del mes</div></div><div class="zf-stat"><div class="n">${money(pending)}</div><div class="l">Pagos pendientes</div></div><div class="zf-stat"><div class="n">${active}</div><div class="l">Membresías activas</div></div><div class="zf-stat"><div class="n">${todayClasses.length}</div><div class="l">Clases de hoy</div></div></div><div class="zf-grid2"><section class="zf-card"><h3>Próximas clases</h3><div class="zf-list">${todayClasses.slice(0,6).map(c=>`<div class="zf-item" onclick="openClass('${c.id}')" style="cursor:pointer"><div><b>${time(c.start_time)} · ${esc(c.class_type||'Functional')}</b><div class="small">${esc(c.coaches?.name||'Sin coach')}</div></div><span class="zf-badge ${booked(c.id)>=(c.capacity||10)?'bad':'ok'}">${booked(c.id)}/${c.capacity||10}</span></div>`).join('')||'<div class="zf-empty">No hay clases hoy.</div>'}</div></section><section class="zf-card"><h3>Acciones rápidas</h3><div class="zf-list"><button class="zf-item" onclick="state.page='clients';render()"><div><b>Clientes</b><div class="small">Perfiles y membresías</div></div><span>›</span></button><button class="zf-item" onclick="state.page='agenda';render()"><div><b>Clases / horarios</b><div class="small">Semana y cupos</div></div><span>›</span></button><button class="zf-item" onclick="state.page='coaches';render()"><div><b>Coaches</b><div class="small">Editar y activar</div></div><span>›</span></button><button class="zf-item" onclick="state.page='finance';render()"><div><b>Finanzas</b><div class="small">Pagos y membresías</div></div><span>›</span></button></div></section></div>`;
  }

  async function agenda(){
    setTitle('Clases / horarios');
    const from=state.anchor,to=addDays(from,6);const days=Array.from({length:7},(_,i)=>addDays(from,i));const dn=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];
    const weekClasses=state.classes.filter(c=>c.class_date>=from&&c.class_date<=to&&c.status==='scheduled');const hourPx=58,minHour=5.5;const topAt=t=>(parseInt(String(t).slice(0,2))*60+parseInt(String(t).slice(3,5))-minHour*60)/60*hourPx;const weekLabel=`${date(from)} – ${fullDate(to)}`;
    $('#zfMain').innerHTML=`<div class="zf-head"><div><div class="zf-kicker">AGENDA</div><div class="zf-h1">Clases / horarios</div><div class="zf-sub">${weekLabel} · máximo 10 personas por clase.</div></div><div class="zf-actions"><button class="zf-btn" id="prevW">‹</button><button class="zf-btn" id="todayW">Hoy</button><button class="zf-btn" id="nextW">›</button><button class="zf-btn red" id="seedW">Generar semana</button></div></div><div class="zf-calendar"><div class="zf-cal-inner"><div class="zf-week-head"><div></div>${days.map((d,i)=>`<div><small>${dn[i]}</small><b>${new Date(d+'T12:00:00').getDate()}</b></div>`).join('')}</div><div class="zf-cal-body"><div class="zf-time-col">${Array.from({length:17},(_,i)=>`<span class="zf-time-label" style="top:${i*hourPx}px">${pad(5+i)}:00</span>`).join('')}</div><div class="zf-day-cols">${days.map((d,i)=>{const slots=i===5?slotsSat:i<5?slotsWeek:[];return `<div class="zf-day">${Array.from({length:17},(_,k)=>`<div class="zf-gridline" style="top:${k*hourPx}px"></div>`).join('')}${slots.map(t=>`<button class="zf-slot" style="top:${topAt(t)+4}px" data-new="${d}|${t}">+ ${t}</button>`).join('')}${weekClasses.filter(c=>c.class_date===d).map(c=>{const top=topAt(c.start_time),h=Math.max(44,topAt(c.end_time)-top);return `<div class="zf-class ${booked(c.id)>=(c.capacity||10)?'full':''}" data-id="${c.id}" style="top:${top}px;height:${h}px"><strong>${time(c.start_time)} · ${esc(c.class_type||'Functional')}</strong><small>${esc(c.coaches?.name||'Sin coach')} · ${booked(c.id)}/${c.capacity||10}</small></div>`}).join('')}</div>`}).join('')}</div></div></div></div>`;
    $('#prevW').onclick=()=>{state.anchor=addDays(state.anchor,-7);render()};$('#nextW').onclick=()=>{state.anchor=addDays(state.anchor,7);render()};$('#todayW').onclick=()=>{state.anchor=monday(today());render()};$('#seedW').onclick=seedWeek;document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>{const [d,t]=b.dataset.new.split('|');openClass(null,d,t)});document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openClass(b.dataset.id));
  }
  const minutes=t=>{const p=String(t||'00:00').split(':').map(Number);return p[0]*60+p[1]};
  async function seedWeek(){for(let i=0;i<6;i++){const d=addDays(state.anchor,i),slots=i===5?slotsSat:slotsWeek;for(const start of slots){const {data:exist}=await db.from('classes').select('id').eq('class_date',d).eq('start_time',start).eq('status','scheduled').limit(1);if(!exist?.length){const end=minutes(start)+60;await db.from('classes').insert({class_date:d,start_time:start,end_time:pad(Math.floor(end/60))+':'+pad(end%60),duration_minutes:60,class_type:'Functional',capacity:10,status:'scheduled'});}}}await load();render()}

  function clients(){setTitle('Clientes');$('#zfMain').innerHTML=`<div class="zf-head"><div><div class="zf-kicker">CLIENTES</div><div class="zf-h1">Clientes</div><div class="zf-sub">Consulta perfiles, membresías y pagos.</div></div></div><div class="zf-card"><input class="zf-search" id="cSearch" placeholder="Buscar nombre o correo"><div class="zf-table" style="margin-top:14px"><table><thead><tr><th>Cliente</th><th>Teléfono</th><th>Nacimiento</th><th>Membresía</th><th></th></tr></thead><tbody id="cBody"></tbody></table></div></div>`;const draw=()=>{const q=($('#cSearch').value||'').toLowerCase();const rows=state.clients.filter(c=>`${c.full_name||''} ${c.email||''}`.toLowerCase().includes(q));$('#cBody').innerHTML=rows.length?rows.map(c=>{const m=state.memberships.find(x=>x.profile_id===c.id&&x.status==='active');return `<tr><td><b>${esc(c.full_name||'')}</b><div class="zf-muted">${esc(c.email||'')}</div></td><td>${esc(c.phone||'—')}</td><td>${fullDate(c.birth_date)}</td><td><span class="zf-badge ${m?'ok':'warn'}">${esc(m?.membership_plans?.name||'Sin membresía')}</span></td><td><button class="zf-btn" onclick="openClient('${c.id}')">Ver</button></td></tr>`}).join(''):'<tr><td colspan="5"><div class="zf-empty">No hay clientes.</div></td></tr>'};$('#cSearch').oninput=draw;draw()}
  function coaches(){setTitle('Coaches');$('#zfMain').innerHTML=`<div class="zf-head"><div><div class="zf-kicker">EQUIPO</div><div class="zf-h1">Coaches</div><div class="zf-sub">Mantén el equipo activo y su información.</div></div><button class="zf-btn red" onclick="openCoach()">+ Coach</button></div><div class="zf-grid2">${state.coaches.map(c=>`<div class="zf-card"><div style="display:flex;justify-content:space-between;gap:10px"><div><h3 style="margin-bottom:4px">${esc(c.name||'')}</h3><div class="zf-muted">${esc(c.specialty||'Coach ZONA 33')}</div></div><span class="zf-badge ${c.is_active===false?'bad':'ok'}">${c.is_active===false?'Inactivo':'Activo'}</span></div><p class="zf-muted" style="min-height:34px;margin:14px 0">${esc(c.bio||'')}</p><div class="zf-actions"><button class="zf-btn" onclick="openCoach('${c.id}')">Editar</button><button class="zf-btn" onclick="toggleCoach('${c.id}',${c.is_active!==false})">${c.is_active===false?'Activar':'Desactivar'}</button></div></div>`).join('')||'<div class="zf-empty">Sin coaches.</div>'}</div>`}

  function finance(){setTitle('Finanzas');const inc=state.payments.filter(p=>p.status==='approved').reduce((s,p)=>s+Number(p.amount||0),0),out=state.expenses.reduce((s,e)=>s+Number(e.amount||0),0),pending=state.payments.filter(p=>p.status==='pending').reduce((s,p)=>s+Number(p.amount||0),0);$('#zfMain').innerHTML=`<div class="zf-head"><div><div class="zf-kicker">CONTROL FINANCIERO</div><div class="zf-h1">Finanzas</div><div class="zf-sub">Ingresos, egresos, membresías y pagos.</div></div><button class="zf-btn red" onclick="openPayment()">Registrar pago</button></div><div class="zf-grid4"><div class="zf-stat"><div class="n">${money(inc)}</div><div class="l">Ingresos</div></div><div class="zf-stat"><div class="n">${money(out)}</div><div class="l">Egresos</div></div><div class="zf-stat"><div class="n">${money(inc-out)}</div><div class="l">Balance</div></div><div class="zf-stat"><div class="n">${money(pending)}</div><div class="l">Pendientes</div></div></div><div class="zf-tabs">${[['payments','Pagos'],['memberships','Membresías'],['plans','Planes'],['founders','Fundadores']].map(([k,l])=>`<button class="zf-tab ${state.tab===k?'active':''}" data-tab="${k}">${l}</button>`).join('')}</div><div id="finbody"></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;finance()});financeTab()}
  function financeTab(){const b=$('#finbody');if(!b)return;if(state.tab==='payments'){b.innerHTML=`<div class="zf-table"><table><thead><tr><th>Cliente</th><th>Concepto</th><th>Monto</th><th>Fecha</th><th>Método</th><th>Estado</th><th></th></tr></thead><tbody>${state.payments.map(p=>`<tr><td><b>${esc(p.profiles?.full_name||'Cliente')}</b><div class="zf-muted">${esc(p.profiles?.email||'')}</div></td><td>${esc(p.concept||p.membership_plans?.name||'Membresía')}</td><td><b>${money(p.amount)}</b></td><td>${fullDate(p.payment_date)}</td><td>${esc(p.method||'—')}</td><td><span class="zf-badge ${p.status==='approved'?'ok':p.status==='pending'?'warn':'bad'}">${p.status==='approved'?'Pagado':p.status==='pending'?'Pendiente':'Rechazado'}</span></td><td><button class="zf-btn" onclick="openPayment('${p.id}')">Ver</button></td></tr>`).join('')||'<tr><td colspan="7"><div class="zf-empty">Sin pagos registrados.</div></td></tr>'}</tbody></table></div>`}else if(state.tab==='memberships'){b.innerHTML=`<div class="zf-table"><table><thead><tr><th>Cliente</th><th>Plan</th><th>Inicio</th><th>Vence</th><th>Estado</th></tr></thead><tbody>${state.memberships.map(m=>`<tr><td>${esc(m.profiles?.full_name||'')}</td><td>${esc(m.membership_plans?.name||'')}</td><td>${fullDate(m.start_date)}</td><td>${fullDate(m.end_date)}</td><td>${esc(m.status||'')}</td></tr>`).join('')||'<tr><td colspan="5"><div class="zf-empty">Sin membresías.</div></td></tr>'}</tbody></table></div>`}else if(state.tab==='plans'){b.innerHTML=`<div class="zf-grid2">${state.plans.map(p=>`<div class="zf-card"><div class="zf-kicker">${p.is_founder_plan?'PLAN FUNDADORES':'PLAN'}</div><h3>${esc(p.name||'')}</h3><div style="font-size:28px;font-weight:650">${money(p.is_founder_plan?500:p.price)}</div><div class="zf-muted">${p.duration_days||30} días · ${p.is_active===false?'Inactivo':'Activo'}</div></div>`).join('')||'<div class="zf-empty">Sin planes.</div>'}</div>`}else{b.innerHTML=`<div class="zf-table"><table><thead><tr><th>Código</th><th>Estado</th><th>Creado</th><th></th></tr></thead><tbody>${state.founders.map(f=>`<tr><td><b>${esc(f.code)}</b></td><td><span class="zf-badge ${f.is_active===false?'bad':f.used_by?'warn':'ok'}">${f.is_active===false?'Inactivo':f.used_by?'Usado':'Activo'}</span></td><td>${fullDate(String(f.created_at||'').slice(0,10))}</td><td><button class="zf-btn" onclick="toggleFounder('${f.id}',${f.is_active!==false})">${f.is_active===false?'Activar':'Desactivar'}</button></td></tr>`).join('')||'<tr><td colspan="4"><div class="zf-empty">Sin códigos.</div></td></tr>'}</tbody></table></div>`}}

  function landing(){setTitle('Editar Landing');$('#zfMain').innerHTML=`<div class="zf-head"><div><div class="zf-kicker">SITIO PÚBLICO</div><div class="zf-h1">Editar Landing</div><div class="zf-sub">Los cambios se guardan en el contenido del sitio.</div></div><button class="zf-btn" onclick="location.href='https://zona33.pages.dev/'">Ver sitio</button></div><div class="zf-card"><div class="zf-empty">La edición de contenido público permanece en el módulo actual conectado al landing.</div></div>`}
  function render(){drawMenu();if(state.page==='dashboard')dashboard();else if(state.page==='agenda')agenda();else if(state.page==='clients')clients();else if(state.page==='coaches')coaches();else if(state.page==='finance')finance();else landing()}

  function showDrawer(title,html){$('#zfDrawer').innerHTML=`<div class="zf-drawer-head"><div><div class="zf-kicker">ZONA 33</div><h3 style="margin:4px 0 0">${title}</h3></div><button class="zf-btn close" id="zfClose">Cerrar</button></div>${html}`;$('#zfDrawerBg').classList.add('show');$('#zfClose').onclick=closeDrawer}
  function closeDrawer(){$('#zfDrawerBg').classList.remove('show')}
  function openClass(id,d,t){if(!id){openClassForm(null,d,t);return}const c=state.classes.find(x=>x.id===id);if(!c)return;const rs=state.reservations.filter(r=>r.class_id===id&&r.status==='reserved');showDrawer(c.class_type||'Clase',`<div class="zf-card" style="margin-top:16px"><div class="zf-row"><div><div class="zf-muted">Fecha</div><b>${fullDate(c.class_date)}</b></div><div><div class="zf-muted">Hora</div><b>${time(c.start_time)}–${time(c.end_time)}</b></div></div><div style="margin-top:12px" class="zf-muted">Coach: ${esc(c.coaches?.name||'Sin coach')} · Cupo: ${c.capacity||10}</div></div><div class="zf-card" style="margin-top:10px"><h3>Reservas (${rs.length}/${c.capacity||10})</h3><div class="zf-list">${rs.map(r=>`<div class="zf-item"><div><b>${esc(r.profiles?.full_name||'Cliente')}</b><div class="small">${esc(r.profiles?.email||'')} · ${esc(r.profiles?.phone||'')}</div></div><span class="zf-badge ok">Reservada</span></div>`).join('')||'<div class="zf-empty">Sin reservas.</div>'}</div></div><div class="zf-actions" style="margin-top:12px"><button class="zf-btn primary" onclick="closeDrawer();openClassForm('${id}','${c.class_date}','${time(c.start_time)}')">Editar</button><button class="zf-btn" onclick="cancelClass('${id}')">Cancelar clase</button></div>`)}
  function openClassForm(id,d,t){const c=id?state.classes.find(x=>x.id===id):{class_date:d||today(),start_time:t||'08:00',end_time:'09:00',class_type:'Functional',duration_minutes:60,capacity:10,coach_id:null};showDrawer(id?'Editar clase':'Nueva clase',`<form id="cf" class="zf-form"><div class="zf-row"><label>Tipo<select id="fType">${['Functional','Strength','Mobility','Conditioning','Open Box','Personal'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Fecha<input id="fDate" type="date" required></label></div><div class="zf-row"><label>Hora<input id="fTime" type="time" required></label><label>Duración<select id="fDur"><option value="60">60 min</option><option value="45">45 min</option><option value="90">90 min</option></select></label></div><label>Coach<select id="fCoach"><option value="">Sin coach</option>${state.coaches.filter(x=>x.is_active!==false).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><label>Capacidad<input id="fCap" type="number" min="1" max="10"></label><div class="zf-actions"><button type="button" class="zf-btn" onclick="closeDrawer()">Cancelar</button><button class="zf-btn red">Guardar clase</button></div></form>`);$('#fType').value=c.class_type||'Functional';$('#fDate').value=c.class_date||today();$('#fTime').value=time(c.start_time);$('#fDur').value=String(c.duration_minutes||60);$('#fCoach').value=c.coach_id||'';$('#fCap').value=Math.min(10,Number(c.capacity||10));$('#cf').onsubmit=async e=>{e.preventDefault();const start=$('#fTime').value,dur=Number($('#fDur').value),end=minutes(start)+dur,payload={class_type:$('#fType').value,class_date:$('#fDate').value,start_time:start,end_time:pad(Math.floor(end/60))+':'+pad(end%60),duration_minutes:dur,coach_id:$('#fCoach').value||null,capacity:Math.min(10,Math.max(1,Number($('#fCap').value||10))),status:'scheduled'};const r=id?await db.from('classes').update(payload).eq('id',id):await db.from('classes').insert(payload);if(r.error)return alert(r.error.message);closeDrawer();await load();render()}}
  function openPayment(id){const p=id?state.payments.find(x=>x.id===id):null;showDrawer(p?'Editar pago':'Registrar pago',`<form id="pf" class="zf-form"><div class="zf-row"><label>Cliente<select id="pClient">${state.clients.map(c=>`<option value="${c.id}">${esc(c.full_name)} — ${esc(c.email||'')}</option>`).join('')}</select></label><label>Concepto<input id="pConcept"></label></div><div class="zf-row"><label>Monto<input id="pAmount" type="number" min="0"></label><label>Fecha<input id="pDate" type="date"></label></div><div class="zf-row"><label>Método<select id="pMethod"><option>transferencia</option><option>efectivo</option><option>tarjeta</option><option>online</option><option>ficha</option></select></label><label>Estado<select id="pStatus"><option value="approved">Pagado</option><option value="pending">Pendiente</option><option value="rejected">Rechazado</option></select></label></div><label>Notas<textarea id="pNotes"></textarea></label><div class="zf-muted">Plan Fundadores: $500 mensuales.</div><div class="zf-actions"><button type="button" class="zf-btn" onclick="closeDrawer()">Cancelar</button><button class="zf-btn red">Guardar pago</button></div></form>`);$('#pClient').value=p?.profile_id||state.clients[0]?.id||'';$('#pConcept').value=p?.concept||'Mensualidad';$('#pAmount').value=String(p?.amount??500);$('#pDate').value=p?.payment_date||today();$('#pMethod').value=p?.method||'transferencia';$('#pStatus').value=p?.status||'approved';$('#pNotes').value=p?.notes||'';$('#pf').onsubmit=async e=>{e.preventDefault();const payload={profile_id:$('#pClient').value,concept:$('#pConcept').value.trim(),amount:Number($('#pAmount').value||0),payment_date:$('#pDate').value,method:$('#pMethod').value,status:$('#pStatus').value,notes:$('#pNotes').value.trim()||null};const r=p?await db.from('payments').update(payload).eq('id',id):await db.from('payments').insert(payload);if(r.error)return alert(r.error.message);closeDrawer();await load();state.tab='payments';state.page='finance';render()}}
  function openClient(id){const c=state.clients.find(x=>x.id===id);if(!c)return;const m=state.memberships.find(x=>x.profile_id===id&&x.status==='active');showDrawer('Cliente',`<div class="zf-card" style="margin-top:16px"><b>${esc(c.full_name||'')}</b><div class="zf-muted">${esc(c.email||'')} · ${esc(c.phone||'')}</div><div class="zf-muted" style="margin-top:4px">Nacimiento: ${fullDate(c.birth_date)}</div></div><div class="zf-card" style="margin-top:10px"><b>Membresía</b><div class="zf-muted" style="margin-top:5px">${m?esc(m.membership_plans?.name||'Activa'):'Sin membresía activa'}</div></div>`)}
  function openCoach(id){const c=id?state.coaches.find(x=>x.id===id):{};showDrawer(id?'Editar coach':'Nuevo coach',`<form id="cof" class="zf-form"><label>Nombre<input id="coName" required></label><label>Especialidad<input id="coSpec"></label><label>Foto URL<input id="coPhoto"></label><label>Bio<textarea id="coBio"></textarea></label><div class="zf-actions"><button type="button" class="zf-btn" onclick="closeDrawer()">Cancelar</button><button class="zf-btn red">Guardar</button></div></form>`);$('#coName').value=c.name||'';$('#coSpec').value=c.specialty||'';$('#coPhoto').value=c.photo_url||'';$('#coBio').value=c.bio||'';$('#cof').onsubmit=async e=>{e.preventDefault();const payload={name:$('#coName').value.trim(),specialty:$('#coSpec').value.trim()||null,photo_url:$('#coPhoto').value.trim()||null,bio:$('#coBio').value.trim()||null,is_active:true};const r=id?await db.from('coaches').update(payload).eq('id',id):await db.from('coaches').insert(payload);if(r.error)return alert(r.error.message);closeDrawer();await load();render()}}
  async function toggleCoach(id,active){const r=await db.from('coaches').update({is_active:active,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert(r.error.message);await load();render()}
  async function toggleFounder(id,active){const r=await db.from('founder_codes').update({is_active:!active}).eq('id',id);if(r.error)return alert(r.error.message);await load();render()}
  async function cancelClass(id){if(!confirm('¿Cancelar esta clase?'))return;const r=await db.from('classes').update({status:'cancelled'}).eq('id',id);if(r.error)return alert(r.error.message);closeDrawer();await load();render()}

  async function start(){style();const {data:{user}}=await db.auth.getUser();if(!user)return;const {data:p}=await db.from('profiles').select('*').eq('id',user.id).single();if(!p||p.role!=='admin')return;await load();shell();render()}
  window.addEventListener('load',()=>{setTimeout(start,400)});
  db.auth.onAuthStateChange((evt)=>{if(evt==='SIGNED_IN')setTimeout(start,250)});
})();