(() => {
  'use strict';

  const SB_URL = 'https://ponhllwbvhtczaphfdgw.supabase.co';
  const SB_KEY = 'sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
  const db = window.supabase.createClient(SB_URL, SB_KEY, {
    auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true }
  });

  const state = {
    profile: null,
    page: 'dashboard',
    financeTab: 'payments',
    clients: [],
    coaches: [],
    classes: [],
    reservations: [],
    payments: [],
    memberships: [],
    plans: [],
    founders: [],
    expenses: [],
    site: {}
  };

  const $ = (s) => document.querySelector(s);
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[c]));
  const money = (v) => '$' + Number(v || 0).toLocaleString('es-MX', { minimumFractionDigits: 0, maximumFractionDigits: 0 });
  const today = () => new Date().toISOString().slice(0, 10);
  const addDays = (value, amount) => { const d = new Date(value + 'T12:00:00'); d.setDate(d.getDate() + amount); return d.toISOString().slice(0, 10); };
  const dateText = (v) => v ? new Date(v + 'T12:00:00').toLocaleDateString('es-MX', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
  const timeText = (v) => String(v || '').slice(0, 5);
  const parseMinutes = (v) => { const [h, m] = String(v || '00:00').split(':').map(Number); return h * 60 + (m || 0); };
  const monthStart = () => today().slice(0, 7) + '-01';

  function injectStyle() {
    if ($('#z33-exact-style')) return;
    const style = document.createElement('style');
    style.id = 'z33-exact-style';
    style.textContent = `
      #z33-exact{min-height:100vh;background:#f7f7f8;color:#17181b;font-family:Inter,Arial,sans-serif}
      #z33-exact *{box-sizing:border-box}
      .z33e-top{height:72px;background:#fff;border-bottom:1px solid #e6e6e9;display:flex;align-items:center;padding:0 28px;gap:14px;position:sticky;top:0;z-index:20}
      .z33e-menu{width:38px;height:38px;border:0;background:#fff;border-radius:9px;font-size:23px;display:grid;place-items:center;cursor:pointer;color:#24262a}
      .z33e-menu:hover{background:#f1f1f3}.z33e-top-title{font-size:20px;font-weight:650}.z33e-date{font-size:14px;color:#7b7f87}
      .z33e-actions{margin-left:auto;display:flex;gap:7px}.z33e-btn{min-height:40px;border:1px solid #dedfe3;background:#fff;border-radius:8px;padding:0 13px;font-size:11px;font-weight:650;color:#34373d;cursor:pointer}.z33e-btn.red{background:#d3232d;border-color:#d3232d;color:#fff}.z33e-btn.danger{background:#fff6f5;border-color:#f0d1ce;color:#b42318}
      .z33e-page{max-width:1120px;margin:0 auto;padding:26px 28px 52px}.z33e-kicker{font-size:10px;color:#c91428;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.z33e-h2{font-size:31px;line-height:1.06;margin:5px 0;font-weight:700;letter-spacing:-.035em}.z33e-sub{font-size:13px;color:#7c8189}.z33e-head{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin-bottom:18px}.z33e-head-actions{display:flex;gap:8px}
      .z33e-stats{display:grid;grid-template-columns:1fr 1fr;gap:16px}.z33e-stat{background:#fff;border:1px solid #e1e2e5;border-radius:16px;padding:20px;min-height:140px}.z33e-icon{width:40px;height:40px;border-radius:11px;display:grid;place-items:center;font-size:19px}.z33e-icon.red{background:#fff1f1;color:#d3232d}.z33e-icon.amber{background:#fff8e9;color:#b87900}.z33e-icon.green{background:#e9fbf3;color:#12a46b}.z33e-icon.gray{background:#f1f1f3;color:#34383e}.z33e-value{font-size:31px;line-height:1.1;font-weight:520;margin-top:13px;letter-spacing:-.03em}.z33e-label{font-size:14px;color:#80848c;margin-top:7px}.z33e-wide{margin-top:16px;background:#fff;border:1px solid #e1e2e5;border-radius:16px;padding:22px}.z33e-wide-title{font-size:18px;font-weight:650;margin-bottom:22px}.z33e-bars{display:grid;gap:10px}.z33e-bar{display:grid;grid-template-columns:95px 1fr 80px;align-items:center;gap:9px;font-size:12px;color:#757982}.z33e-track{height:30px;background:#fafafa;border-radius:5px;overflow:hidden}.z33e-fill{height:100%;background:#d9272f;border-radius:5px}.z33e-amount{text-align:right;color:#202226;font-weight:600}
      .z33e-tabs{display:flex;gap:2px;border-bottom:1px solid #e2e3e6;margin:22px 0 16px;overflow:auto}.z33e-tab{border:0;background:transparent;padding:11px 13px;font-size:12px;font-weight:650;color:#777b83;border-bottom:2px solid transparent;white-space:nowrap;cursor:pointer}.z33e-tab.active{color:#c61d28;border-color:#d9272f}
      .z33e-card{background:#fff;border:1px solid #e1e2e5;border-radius:14px;padding:18px}.z33e-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:14px}.z33e-search{height:40px;width:min(370px,100%);border:1px solid #dedfe3;border-radius:9px;padding:0 12px;background:#fff;font-size:12px}.z33e-filter-row{display:flex;gap:6px;flex-wrap:wrap}.z33e-filter{height:36px;border:1px solid #dedfe3;border-radius:8px;background:#fff;padding:0 11px;font-size:11px;cursor:pointer}.z33e-filter.active{background:#fff0f0;border-color:#e8a8ac;color:#b71f28;font-weight:700}
      .z33e-table{overflow:auto;border:1px solid #e1e2e5;border-radius:12px;background:#fff}.z33e-table table{width:100%;min-width:780px;border-collapse:collapse}.z33e-table th{background:#fafafa;color:#777b83;text-transform:uppercase;font-size:9px;letter-spacing:.06em;text-align:left;padding:11px;border-bottom:1px solid #ececef}.z33e-table td{padding:12px 11px;border-bottom:1px solid #f0f0f2;font-size:12px;vertical-align:middle}.z33e-table tr:last-child td{border-bottom:0}.z33e-muted{font-size:10px;color:#858991;margin-top:3px}.z33e-pill{display:inline-flex;border-radius:999px;padding:4px 8px;font-size:9px;font-weight:800}.z33e-pill.ok{background:#e9f8f1;color:#14764c}.z33e-pill.warn{background:#fff7df;color:#866300}.z33e-pill.bad{background:#fdecef;color:#b4232e}
      .z33e-grid2{display:grid;grid-template-columns:1.45fr 1fr;gap:16px}.z33e-list{display:grid;gap:8px}.z33e-item{background:#fafbfc;border:1px solid #eceef0;border-radius:10px;padding:12px;display:flex;align-items:center;justify-content:space-between;gap:10px}.z33e-empty{padding:34px;text-align:center;color:#8a8e95;font-size:12px}.z33e-actions{display:flex;gap:6px;flex-wrap:wrap}
      .z33e-drawer-overlay{position:fixed;inset:0;background:rgba(20,22,26,.28);z-index:90;display:none}.z33e-drawer-overlay.show{display:block}.z33e-drawer{position:fixed;top:0;right:0;bottom:0;width:min(500px,95vw);background:#fff;z-index:91;box-shadow:-18px 0 48px rgba(0,0,0,.15);padding:22px;overflow:auto;transform:translateX(100%);transition:transform .18s}.z33e-drawer.show{transform:translateX(0)}.z33e-drawer-head{display:flex;align-items:flex-start;gap:10px}.z33e-drawer-head h3{font-size:20px;margin:0}.z33e-drawer-head .z33e-btn{margin-left:auto}.z33e-form{display:grid;gap:12px;margin-top:18px}.z33e-form label{font-size:10px;font-weight:700;color:#727780}.z33e-form input,.z33e-form select,.z33e-form textarea{width:100%;margin-top:6px;padding:11px;border:1px solid #dfe1e5;border-radius:9px;background:#fff;font-size:12px}.z33e-form textarea{min-height:100px;resize:vertical}.z33e-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}
      .z33e-calendar{background:#fff;border:1px solid #e1e2e5;border-radius:14px;overflow:auto}.z33e-cal-inner{min-width:980px}.z33e-week-head{display:grid;grid-template-columns:54px repeat(7,1fr);background:#fafafa;border-bottom:1px solid #e6e7e9}.z33e-week-head>div{padding:9px 3px;text-align:center;border-left:1px solid #f0f1f2}.z33e-week-head small{font-size:8px;color:#80858d;text-transform:uppercase}.z33e-week-head b{display:block;margin-top:3px;font-size:13px}.z33e-week-body{display:grid;grid-template-columns:54px 1fr}.z33e-time-col,.z33e-day-col{height:850px;position:relative}.z33e-time{position:absolute;right:7px;transform:translateY(-6px);font-size:8px;color:#959ba2}.z33e-day-cols{display:grid;grid-template-columns:repeat(7,1fr)}.z33e-day-col{border-left:1px solid #f0f1f2}.z33e-hour-line{position:absolute;left:0;right:0;border-top:1px solid #f4f4f5}.z33e-class{position:absolute;left:4px;right:4px;border:1px solid #dfe2e5;border-left:3px solid #2d3136;background:#fff;border-radius:7px;padding:5px;cursor:pointer;overflow:hidden}.z33e-class.full{border-left-color:#c91428;background:#fff1f1}.z33e-class b{font-size:8px}.z33e-class strong{display:block;font-size:9px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.z33e-class small{display:block;color:#858b93;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
      .z33e-menu-drawer{position:fixed;top:0;left:0;bottom:0;width:300px;background:#fff;z-index:92;box-shadow:18px 0 48px rgba(0,0,0,.12);padding:24px;transform:translateX(-100%);transition:transform .18s}.z33e-menu-drawer.show{transform:translateX(0)}.z33e-menu-title{font-size:20px;font-weight:700}.z33e-menu-sub{font-size:12px;color:#858991;margin-top:4px}.z33e-menu-list{display:grid;gap:4px;margin-top:22px}.z33e-menu-item{height:45px;border:0;background:#fff;border-radius:9px;text-align:left;padding:0 12px;font-size:13px;font-weight:600;color:#555a62;cursor:pointer}.z33e-menu-item:hover,.z33e-menu-item.active{background:#fff0f0;color:#b71e28}.z33e-menu-overlay{position:fixed;inset:0;background:rgba(20,22,26,.28);z-index:91;display:none}.z33e-menu-overlay.show{display:block}
      @media(max-width:760px){.z33e-top{padding:0 13px}.z33e-actions{display:none}.z33e-page{padding:18px 12px 40px}.z33e-stats{grid-template-columns:1fr}.z33e-grid2{grid-template-columns:1fr}.z33e-row{grid-template-columns:1fr}.z33e-bar{grid-template-columns:72px 1fr 68px}.z33e-menu-drawer{width:86vw}}
    `;
    document.head.appendChild(style);
  }

  function shell(title, date) {
    document.body.innerHTML = `<div id="z33-exact"><header class="z33e-top"><button class="z33e-menu" id="z33e-open-menu">☰</button><div class="z33e-top-title">${esc(title)}</div><span class="z33e-date">· ${esc(date || '')}</span><div class="z33e-actions"><button class="z33e-btn" onclick="location.href='https://zona33.pages.dev/'">Sitio</button><button class="z33e-btn danger" id="z33e-logout">Salir</button></div></header><main id="z33e-content"></main><div id="z33e-menu-overlay" class="z33e-menu-overlay"></div><aside id="z33e-menu-drawer" class="z33e-menu-drawer"><div class="z33e-menu-title">ZONA 33</div><div class="z33e-menu-sub">Panel administrativo</div><div class="z33e-menu-list">${menuItems()}</div></aside><div id="z33e-drawer-overlay" class="z33e-drawer-overlay"><aside id="z33e-drawer" class="z33e-drawer"></aside></div></div>`;
    injectStyle();
    $('#z33e-open-menu').onclick = openMenu;
    $('#z33e-menu-overlay').onclick = closeMenu;
    $('#z33e-logout').onclick = async () => { await db.auth.signOut(); location.reload(); };
    document.querySelectorAll('.z33e-menu-item').forEach((b) => b.onclick = () => { closeMenu(); route(b.dataset.page); });
  }

  function menuItems() {
    const items = [['dashboard','Dashboard'],['clients','Clientes'],['agenda','Clases / Horarios'],['coaches','Coaches'],['finance','Finanzas'],['landing','Editar Landing']];
    return items.map(([k,v]) => `<button class="z33e-menu-item ${state.page === k ? 'active' : ''}" data-page="${k}">${v}</button>`).join('');
  }

  function openMenu(){ $('#z33e-menu-drawer')?.classList.add('show'); $('#z33e-menu-overlay')?.classList.add('show'); }
  function closeMenu(){ $('#z33e-menu-drawer')?.classList.remove('show'); $('#z33e-menu-overlay')?.classList.remove('show'); }

  async function loadData() {
    const [clients, coaches, classes, reservations, payments, memberships, plans, founders, expenses, site] = await Promise.all([
      db.from('profiles').select('*').eq('role','cliente').order('created_at', { ascending:false }),
      db.from('coaches').select('*').order('is_active',{ascending:false}).order('name'),
      db.from('classes').select('*').gte('class_date', today()).order('class_date').order('start_time'),
      db.from('reservations').select('id,class_id,profile_id,status,created_at,profiles(full_name,email,phone)').order('created_at',{ascending:false}),
      db.from('payments').select('*,profiles(full_name,email),membership_plans(name,is_founder_plan)').order('payment_date',{ascending:false}).order('created_at',{ascending:false}),
      db.from('memberships').select('*,profiles(full_name,email),membership_plans(name,price,is_founder_plan)').order('created_at',{ascending:false}),
      db.from('membership_plans').select('*').order('sort_order').order('name'),
      db.from('founder_codes').select('*').order('created_at',{ascending:false}),
      db.from('expenses').select('*').order('expense_date',{ascending:false}).order('created_at',{ascending:false}),
      db.from('site_content').select('*').order('key')
    ]);
    state.clients=clients.data||[]; state.coaches=coaches.data||[]; state.classes=(classes.data||[]).map(c=>({...c,coach:state.coaches.find(x=>x.id===c.coach_id)})); state.reservations=reservations.data||[]; state.payments=payments.data||[]; state.memberships=memberships.data||[]; state.plans=plans.data||[]; state.founders=founders.data||[]; state.expenses=expenses.data||[]; state.site=Object.fromEntries((site.data||[]).map(x=>[x.key,x.value]));
  }

  function setContent(html,title,date='') { const root=$('#z33-exact-content'); if(root)root.innerHTML=html; const t=$('.z33e-top-title');const d=$('.z33e-date');if(t)t.textContent=title;if(d)d.textContent='· '+date; document.querySelectorAll('.z33e-menu-item').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page)); }

  function stat(icon,cls,value,label,isMoney=true){ return `<div class="z33e-stat"><div class="z33e-icon ${cls}">${icon}</div><div class="z33e-value">${isMoney?money(value):value}</div><div class="z33e-label">${label}</div></div>`; }

  async function dashboard(){
    const active=state.memberships.filter(m=>m.status==='active'&&m.end_date>=today()).length;
    const founders=state.memberships.filter(m=>m.status==='active'&&m.membership_plans?.is_founder_plan).length;
    const pending=state.payments.filter(p=>p.status==='pending').length;
    const income=state.payments.filter(p=>p.status==='approved'&&String(p.payment_date||'')>=monthStart()).reduce((s,p)=>s+Number(p.amount||0),0);
    setContent(`<div class="z33e-page"><div class="z33e-head"><div><div class="z33e-kicker">ZONA 33</div><div class="z33e-h2">Dashboard</div><div class="z33e-sub">Resumen de operación.</div></div><div class="z33e-head-actions"><button class="z33e-btn red" onclick="z33NewClass()">+ Clase</button><button class="z33e-btn" onclick="route('finance')">Registrar pago</button></div></div><div class="z33e-stats">${stat('↗','red',income,'Ingresos del mes')}${stat('◷','amber',pending,'Pagos pendientes',false)}${stat('♧','green',active,'Membresías activas',false)}${stat('▣','amber',founders,'Fundadores activos',false)}</div><div class="z33e-grid2" style="margin-top:16px"><div class="z33e-card"><div class="z33e-kicker">Próximas clases</div><h3 style="margin:5px 0 14px">Agenda inmediata</h3><div class="z33e-list">${state.classes.slice(0,6).map(c=>{const booked=state.reservations.filter(r=>r.class_id===c.id&&r.status==='reserved').length;return `<div class="z33e-item" onclick="openClass('${c.id}')" style="cursor:pointer"><div><b>${timeText(c.start_time)} · ${esc(c.class_type||'Functional')}</b><div class="z33e-muted">${dateText(c.class_date)} · ${esc(c.coach?.name||'Sin coach')}</div></div><span class="z33e-pill ${booked>=Number(c.capacity||10)?'bad':'ok'}">${booked}/${Number(c.capacity||10)}</span></div>`}).join('')||'<div class="z33e-empty">No hay clases próximas.</div>'}</div></div><div class="z33e-card"><div class="z33e-kicker">Administración</div><h3 style="margin:5px 0 14px">Accesos</h3><div class="z33e-list">${[['clients','Clientes'],['agenda','Clases / Horarios'],['coaches','Coaches'],['finance','Finanzas'],['landing','Editar Landing']].map(([k,v])=>`<button class="z33e-btn" style="text-align:left" onclick="route('${k}')">${v}</button>`).join('')}</div></div></div></div>`, 'Dashboard', currentDate());
  }

  function currentDate(){ return new Date().toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'}).replace(/^./,x=>x.toUpperCase()); }

  function clients(){
    setContent(`<div class="z33e-page"><div class="z33e-head"><div><div class="z33e-kicker">Operación</div><div class="z33e-h2">Clientes</div><div class="z33e-sub">Consulta cuentas, membresías, reservas y pagos.</div></div></div><div class="z33e-card"><div class="z33e-toolbar"><input id="z33e-client-search" class="z33e-search" placeholder="Buscar por nombre, correo o teléfono"><span class="z33e-muted">${state.clients.length} clientes</span></div><div class="z33e-table"><table><thead><tr><th>Cliente</th><th>Teléfono</th><th>Fecha de nacimiento</th><th>Alta</th><th></th></tr></thead><tbody id="z33e-client-body"></tbody></table></div></div></div>`, 'Clientes', currentDate());
    const draw=(rows)=>$('#z33e-client-body').innerHTML=rows.length?rows.map(c=>`<tr><td><b>${esc(c.full_name||'Sin nombre')}</b><div class="z33e-muted">${esc(c.email||'')}</div></td><td>${esc(c.phone||'—')}</td><td>${dateText(c.birth_date)}</td><td>${dateText(String(c.created_at||'').slice(0,10))}</td><td><button class="z33e-btn" onclick="openClient('${c.id}')">Ver</button></td></tr>`).join(''):'<tr><td colspan="5" class="z33e-empty">Sin clientes.</td></tr>';
    draw(state.clients); $('#z33e-client-search').oninput=e=>{const q=e.target.value.toLowerCase();draw(state.clients.filter(c=>`${c.full_name||''} ${c.email||''} ${c.phone||''}`.toLowerCase().includes(q)))};
  }

  function weekStart(value){ const d=new Date(value+'T12:00:00'); const n=d.getDay(); d.setDate(d.getDate()+(n===0?-6:1-n)); return d.toISOString().slice(0,10); }
  function agenda(week=today()){
    const start=weekStart(week);const days=Array.from({length:7},(_,i)=>addDays(start,i));const labels=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];const hours=Array.from({length:16},(_,i)=>6+i);
    const heads=days.map((d,i)=>`<div><small>${labels[i]}</small><b>${new Date(d+'T12:00:00').getDate()}</b></div>`).join('');
    const times=hours.map(h=>`<div class="z33e-time" style="top:${(h-6)*52}px">${String(h).padStart(2,'0')}:00</div>`).join('');
    const cols=days.map(day=>{const rows=state.classes.filter(c=>c.class_date===day&&c.status==='scheduled').map(c=>{const top=(parseMinutes(c.start_time)-360)/60*52;const h=Math.max(38,(Number(c.duration_minutes||60)/60)*52-4);const booked=state.reservations.filter(r=>r.class_id===c.id&&r.status==='reserved').length;return `<div class="z33e-class ${booked>=Number(c.capacity||10)?'full':''}" style="top:${top}px;height:${h}px" onclick="openClass('${c.id}')"><b>${timeText(c.start_time)}</b><strong>${esc(c.class_type||'Functional')}</strong><small>${booked}/${Number(c.capacity||10)} · ${esc(c.coach?.name||'Sin coach')}</small></div>`}).join('');return `<div class="z33e-day-col">${hours.map(h=>`<div class="z33e-hour-line" style="top:${(h-6)*52}px"></div>`).join('')}${rows}</div>`}).join('');
    setContent(`<div class="z33e-page"><div class="z33e-head"><div><div class="z33e-kicker">Agenda</div><div class="z33e-h2">Clases</div><div class="z33e-sub">Haz clic en una clase para ver sus reservas.</div></div><div class="z33e-head-actions"><button class="z33e-btn" onclick="agenda('${addDays(start,-7)}')">‹</button><button class="z33e-btn" onclick="agenda('${today()}')">Hoy</button><button class="z33e-btn" onclick="agenda('${addDays(start,7)}')">›</button><button class="z33e-btn red" onclick="z33NewClass()">+ Clase</button></div></div><div class="z33e-calendar"><div class="z33e-cal-inner"><div class="z33e-week-head"><div></div>${heads}</div><div class="z33e-week-body"><div class="z33e-time-col">${times}</div><div class="z33e-day-cols">${cols}</div></div></div></div></div>`, 'Clases / Horarios', currentDate());
  }

  function coaches(){
    setContent(`<div class="z33e-page"><div class="z33e-head"><div><div class="z33e-kicker">Operación</div><div class="z33e-h2">Coaches</div><div class="z33e-sub">Edita, activa y desactiva coaches.</div></div><button class="z33e-btn red" onclick="coachForm()">+ Coach</button></div><div class="z33e-grid2">${state.coaches.map(c=>`<div class="z33e-card"><div style="display:flex;gap:10px;align-items:center"><div style="width:42px;height:42px;border-radius:50%;background:#f0f0f2;display:grid;place-items:center;overflow:hidden;font-weight:800">${c.photo_url?`<img src="${esc(c.photo_url)}" style="width:100%;height:100%;object-fit:cover">`:esc((c.name||'?')[0])}</div><div><b>${esc(c.name)}</b><div class="z33e-muted">${esc(c.specialty||'Coach')}</div></div></div><p class="z33e-muted" style="line-height:1.5">${esc(c.bio||'')}</p><span class="z33e-pill ${c.is_active?'ok':'bad'}">${c.is_active?'Activo':'Inactivo'}</span><div class="z33e-actions" style="margin-top:12px"><button class="z33e-btn" onclick="coachForm('${c.id}')">Editar</button><button class="z33e-btn danger" onclick="toggleCoach('${c.id}',${!c.is_active})">${c.is_active?'Eliminar':'Reactivar'}</button></div></div>`).join('')}</div></div>`, 'Coaches', currentDate());
  }

  async function finance(tab=state.financeTab){
    state.financeTab=tab;
    const start=monthStart();const approved=state.payments.filter(p=>p.status==='approved'&&String(p.payment_date||'')>=start);const pending=state.payments.filter(p=>p.status==='pending');const income=approved.reduce((s,p)=>s+Number(p.amount||0),0);const pendingAmount=pending.reduce((s,p)=>s+Number(p.amount||0),0);const active=state.memberships.filter(m=>m.status==='active'&&m.end_date>=today()).length;const expiring=state.memberships.filter(m=>m.status==='active'&&m.end_date>=today()&&m.end_date<=addDays(today(),7)).length;const newClients=state.clients.filter(c=>String(c.created_at||'').slice(0,10)>=start).length;
    const grouped={};approved.forEach(p=>{const d=String(p.payment_date||'').slice(0,10);grouped[d]=(grouped[d]||0)+Number(p.amount||0)});const bars=Object.entries(grouped).sort((a,b)=>a[0].localeCompare(b[0]));const max=Math.max(1,...bars.map(x=>x[1]));
    setContent(`<div class="z33e-page"><div class="z33e-stats">${stat('↗','red',income,'Ingresos del periodo')}${stat('◷','amber',pendingAmount,'Pagos pendientes')}${stat('♧','green',active,'Membresías activas',false)}${stat('▣','amber',expiring,'Por vencer',false)}${stat('＋','gray',newClients,'Nuevos clientes',false)}</div><div class="z33e-wide"><div class="z33e-wide-title">Ingresos por día</div><div class="z33e-bars">${bars.length?bars.map(([d,v])=>`<div class="z33e-bar"><span>${esc(d)}</span><div class="z33e-track"><div class="z33e-fill" style="width:${Math.max(4,v/max*100)}%"></div></div><span class="z33e-amount">${money(v)}</span></div>`).join(''):'<div class="z33e-empty">No hay ingresos registrados en este periodo.</div>'}</div></div><div class="z33e-tabs">${[['payments','Pagos'],['memberships','Membresías'],['plans','Planes'],['founders','Códigos fundadores'],['reports','Reportes']].map(([k,v])=>`<button class="z33e-tab ${tab===k?'active':''}" onclick="finance('${k}')">${v}</button>`).join('')}</div><div id="z33e-finance-body"></div></div>`, 'Finanzas', currentDate());
    financeBody(tab);
  }

  function financeBody(tab){
    const body=$('#z33e-finance-body');
    if(tab==='payments'){
      body.innerHTML=`<div class="z33e-card"><div class="z33e-toolbar"><input id="z33e-pay-search" class="z33e-search" placeholder="Buscar cliente o concepto"><div class="z33e-actions"><button class="z33e-btn" onclick="paymentForm()">Registrar pago</button><button class="z33e-btn red" onclick="expenseForm()">Nuevo egreso</button></div></div><div class="z33e-filter-row" style="margin-bottom:12px"><button class="z33e-filter active" onclick="paymentFilter(this,'all')">Todos</button><button class="z33e-filter" onclick="paymentFilter(this,'approved')">Pagados</button><button class="z33e-filter" onclick="paymentFilter(this,'pending')">Pendientes</button><button class="z33e-filter" onclick="paymentFilter(this,'overdue')">Vencidos</button></div><div class="z33e-table"><table><thead><tr><th>Cliente</th><th>Concepto</th><th>Monto</th><th>Fecha</th><th>Método</th><th>Estado</th><th></th></tr></thead><tbody id="z33e-pay-body"></tbody></table></div></div>`;
      const draw=(rows)=>$('#z33e-pay-body').innerHTML=rows.length?rows.map(p=>`<tr><td><b>${esc(p.profiles?.full_name||'Cliente')}</b><div class="z33e-muted">${esc(p.profiles?.email||'')}</div></td><td>${esc(p.concept||p.membership_plans?.name||'Membresía')}</td><td><b>${money(p.amount)}</b></td><td>${dateText(p.payment_date)}</td><td>${esc(p.method||'—')}</td><td><span class="z33e-pill ${p.status==='approved'?'ok':p.status==='pending'?'warn':'bad'}">${p.status==='approved'?'Pagado':p.status==='pending'?'Pendiente':'Rechazado'}</span></td><td><button class="z33e-btn" onclick="paymentForm('${p.id}')">Ver</button></td></tr>`).join(''):'<tr><td colspan="7" class="z33e-empty">Sin pagos.</td></tr>';
      draw(state.payments);$('#z33e-pay-search').oninput=e=>{const q=e.target.value.toLowerCase();draw(state.payments.filter(p=>`${p.profiles?.full_name||''} ${p.profiles?.email||''} ${p.concept||''}`.toLowerCase().includes(q)))};
    } else if(tab==='memberships'){
      body.innerHTML=`<div class="z33e-card"><div class="z33e-toolbar"><input class="z33e-search" id="z33e-mem-search" placeholder="Buscar cliente"><span class="z33e-muted">${state.memberships.length} membresías</span></div><div class="z33e-table"><table><thead><tr><th>Cliente</th><th>Plan</th><th>Inicio</th><th>Vence</th><th>Estado</th></tr></thead><tbody id="z33e-mem-body"></tbody></table></div></div>`;
      const draw=(rows)=>$('#z33e-mem-body').innerHTML=rows.length?rows.map(m=>`<tr><td><b>${esc(m.profiles?.full_name||'')}</b><div class="z33e-muted">${esc(m.profiles?.email||'')}</div></td><td>${esc(m.membership_plans?.name||'—')} ${m.membership_plans?.is_founder_plan?'<span class="z33e-pill ok">$500 FIJO</span>':''}</td><td>${dateText(m.start_date)}</td><td>${dateText(m.end_date)}</td><td><span class="z33e-pill ${m.status==='active'?'ok':'warn'}">${esc(m.status)}</span></td></tr>`).join(''):'<tr><td colspan="5" class="z33e-empty">Sin membresías.</td></tr>';
      draw(state.memberships);$('#z33e-mem-search').oninput=e=>{const q=e.target.value.toLowerCase();draw(state.memberships.filter(m=>`${m.profiles?.full_name||''} ${m.profiles?.email||''} ${m.membership_plans?.name||''}`.toLowerCase().includes(q)))};
    } else if(tab==='plans'){
      body.innerHTML=`<div class="z33e-grid2">${state.plans.map(p=>`<div class="z33e-card"><div class="z33e-kicker">${p.is_founder_plan?'Fundadores':'Plan'}</div><h3 style="margin:6px 0">${esc(p.name)}</h3><div style="font-size:29px;font-weight:650">${money(p.is_founder_plan?500:p.price)}</div><div class="z33e-muted">${esc(p.description||'')} · ${p.duration_days||30} días</div><div class="z33e-actions" style="margin-top:12px"><button class="z33e-btn" onclick="planForm('${p.id}')">Editar</button></div></div>`).join('')}</div>`;
    } else if(tab==='founders'){
      body.innerHTML=`<div class="z33e-card"><div class="z33e-toolbar"><div class="z33e-muted">El Plan Fundadores permanece fijo en $500.</div><button class="z33e-btn red" onclick="founderForm()">+ Código</button></div><div class="z33e-table"><table><thead><tr><th>Código</th><th>Estado</th><th>Creado</th><th>Uso</th><th></th></tr></thead><tbody>${state.founders.length?state.founders.map(f=>`<tr><td><b>${esc(f.code)}</b></td><td><span class="z33e-pill ${f.is_active===false?'bad':f.used_by?'warn':'ok'}">${f.is_active===false?'Inactivo':f.used_by?'Usado':'Activo'}</span></td><td>${dateText(String(f.created_at||'').slice(0,10))}</td><td>${f.used_at?dateText(String(f.used_at).slice(0,10)):'—'}</td><td><div class="z33e-actions"><button class="z33e-btn" onclick="founderForm('${f.id}')">Editar</button>${!f.used_by?`<button class="z33e-btn danger" onclick="toggleFounder('${f.id}',${f.is_active!==false})">${f.is_active===false?'Activar':'Desactivar'}</button>`:''}</div></td></tr>`).join(''):'<tr><td colspan="5" class="z33e-empty">Sin códigos.</td></tr>'}</tbody></table></div></div>`;
    } else {
      const expense=state.expenses.filter(e=>String(e.expense_date||'')>=monthStart()).reduce((s,e)=>s+Number(e.amount||0),0);const inc=state.payments.filter(p=>p.status==='approved').reduce((s,p)=>s+Number(p.amount||0),0);const allExp=state.expenses.reduce((s,e)=>s+Number(e.amount||0),0);
      body.innerHTML=`<div class="z33e-stats">${stat('↗','red',inc,'Ingresos')}${stat('↘','amber',allExp,'Egresos')}${stat('=','gray',inc-allExp,'Balance')}${stat('♧','green',state.founders.filter(f=>f.is_active!==false).length,'Fundadores activos',false)}</div><div class="z33e-grid2" style="margin-top:16px"><div class="z33e-card"><div class="z33e-kicker">Este mes</div><h3>Métricas</h3><div class="z33e-list"><div class="z33e-item"><span>Membresías activas</span><b>${state.memberships.filter(m=>m.status==='active'&&m.end_date>=today()).length}</b></div><div class="z33e-item"><span>Pagos aprobados</span><b>${state.payments.filter(p=>p.status==='approved'&&String(p.payment_date||'')>=monthStart()).length}</b></div><div class="z33e-item"><span>Egresos del mes</span><b>${money(expense)}</b></div></div></div><div class="z33e-card"><div class="z33e-kicker">Últimos egresos</div><h3>Movimientos</h3><div class="z33e-list">${state.expenses.slice(0,7).map(e=>`<div class="z33e-item"><div><b>${esc(e.concept)}</b><div class="z33e-muted">${dateText(e.expense_date)} · ${esc(e.category||'General')}</div></div><b>${money(e.amount)}</b></div>`).join('')||'<div class="z33e-empty">Sin egresos registrados.</div>'}</div></div></div>`;
    }
  }

  function paymentFilter(btn,status){document.querySelectorAll('.z33e-filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const q=($('#z33e-pay-search')?.value||'').toLowerCase();let rows=state.payments.filter(p=>`${p.profiles?.full_name||''} ${p.profiles?.email||''} ${p.concept||''}`.toLowerCase().includes(q));if(status!=='all')rows=rows.filter(p=>status==='overdue'?p.status==='pending'&&String(p.payment_date||'')<today():p.status===status);$('#z33e-pay-body').innerHTML=rows.length?rows.map(p=>`<tr><td><b>${esc(p.profiles?.full_name||'Cliente')}</b><div class="z33e-muted">${esc(p.profiles?.email||'')}</div></td><td>${esc(p.concept||p.membership_plans?.name||'Membresía')}</td><td><b>${money(p.amount)}</b></td><td>${dateText(p.payment_date)}</td><td>${esc(p.method||'—')}</td><td><span class="z33e-pill ${p.status==='approved'?'ok':p.status==='pending'?'warn':'bad'}">${p.status==='approved'?'Pagado':p.status==='pending'?'Pendiente':'Rechazado'}</span></td><td><button class="z33e-btn" onclick="paymentForm('${p.id}')">Ver</button></td></tr>`).join(''):'<tr><td colspan="7" class="z33e-empty">Sin pagos.</td></tr>'}

  function openDrawer(title, html){$('#z33e-drawer-overlay').classList.add('show');$('#z33e-drawer').classList.add('show');$('#z33e-drawer').innerHTML=`<div class="z33e-drawer-head"><div><div class="z33e-kicker">ZONA 33</div><h3>${title}</h3></div><button class="z33e-btn" onclick="closeDrawer()">Cerrar</button></div>${html}`;}
  function closeDrawer(){$('#z33e-drawer-overlay')?.classList.remove('show');$('#z33e-drawer')?.classList.remove('show')}

  function openClient(id){const c=state.clients.find(x=>x.id===id);if(!c)return;const m=state.memberships.find(x=>x.profile_id===id&&x.status==='active');const rs=state.reservations.filter(x=>x.profile_id===id).slice(0,6);const ps=state.payments.filter(x=>x.profile_id===id).slice(0,6);openDrawer('Cliente',`<div class="z33-list"><div class="z33e-card"><b>${esc(c.full_name||'')}</b><div class="z33e-muted">${esc(c.email||'')}<br>${esc(c.phone||'')}</div><div class="z33e-muted">Nacimiento: ${dateText(c.birth_date)}</div></div><div class="z33e-card"><b>Membresía</b><div class="z33e-muted" style="margin-top:6px">${m?`${esc(m.membership_plans?.name||'Plan')} · ${dateText(m.start_date)} → ${dateText(m.end_date)}`:'Sin membresía activa'}</div></div><div class="z33e-card"><b>Reservas recientes</b><div class="z33e-list" style="margin-top:8px">${rs.map(r=>`<div class="z33e-item"><span>${dateText(state.classes.find(x=>x.id===r.class_id)?.class_date)} · ${esc(r.status)}</span></div>`).join('')||'<div class="z33e-empty">Sin reservas.</div>'}</div></div><div class="z33e-card"><b>Pagos recientes</b><div class="z33e-list" style="margin-top:8px">${ps.map(p=>`<div class="z33e-item"><span>${esc(p.concept||'Pago')}<div class="z33e-muted">${dateText(p.payment_date)}</div></span><b>${money(p.amount)}</b></div>`).join('')||'<div class="z33e-empty">Sin pagos.</div>'}</div></div></div>`)}

  function openClass(id){const c=state.classes.find(x=>x.id===id);if(!c)return;const rs=state.reservations.filter(r=>r.class_id===id);const active=rs.filter(r=>r.status==='reserved').length;openDrawer(esc(c.class_type||'Functional'),`<div class="z33e-card"><div class="z33e-row"><div><div class="z33e-muted">Fecha</div><b>${dateText(c.class_date)}</b></div><div><div class="z33e-muted">Hora</div><b>${timeText(c.start_time)} – ${timeText(c.end_time)}</b></div><div><div class="z33e-muted">Capacidad</div><b>${Number(c.capacity||10)} lugares</b></div><div><div class="z33e-muted">Ocupados</div><b>${active}</b></div></div></div><div class="z33e-card" style="margin-top:10px"><b>Coach</b><div class="z33e-muted" style="margin-top:6px">${esc(c.coach?.name||'Sin asignar')}</div></div><div class="z33e-card" style="margin-top:10px"><div style="display:flex;justify-content:space-between"><b>Reservas</b><span class="z33e-muted">${active}/${Number(c.capacity||10)}</span></div><div class="z33e-list" style="margin-top:8px">${rs.map(r=>`<div class="z33e-item"><div><b>${esc(r.profiles?.full_name||'Cliente')}</b><div class="z33e-muted">${esc(r.profiles?.phone||'')} · ${esc(r.profiles?.email||'')}</div></div><span class="z33e-pill ${r.status==='reserved'?'ok':'warn'}">${esc(r.status)}</span></div>`).join('')||'<div class="z33e-empty">Sin reservas.</div>'}</div></div><div class="z33e-actions" style="margin-top:12px"><button class="z33e-btn" onclick="closeDrawer();classForm('${c.id}')">Editar</button><button class="z33e-btn danger" onclick="cancelClass('${c.id}')">Cancelar clase</button></div>`)}

  function z33NewClass(){classForm()}
  function classForm(id){const c=id?state.classes.find(x=>x.id===id):{class_type:'Functional',class_date:today(),start_time:'08:00',duration_minutes:60,capacity:10,coach_id:''};openDrawer(id?'Editar clase':'Nueva clase',`<form id="z33e-class-form" class="z33e-form"><div class="z33e-row"><label>Tipo<select id="cf-type">${['Functional','Strength','Mobility','Conditioning','Open Box','Personal'].map(v=>`<option>${v}</option>`).join('')}</select></label><label>Fecha<input id="cf-date" type="date"></label></div><div class="z33e-row"><label>Hora<input id="cf-time" type="time"></label><label>Duración<select id="cf-duration">${[30,45,60,75,90].map(v=>`<option value="${v}">${v} min</option>`).join('')}</select></label></div><div class="z33e-row"><label>Coach<select id="cf-coach"><option value="">Sin asignar</option>${state.coaches.filter(x=>x.is_active).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><label>Capacidad<input id="cf-cap" type="number" min="1" max="10"></label></div><div class="z33e-muted">Máximo permitido: 10 personas.</div><div class="z33e-actions"><button type="button" class="z33e-btn" onclick="closeDrawer()">Cancelar</button><button class="z33e-btn red">Guardar</button></div></form>`);$('#cf-type').value=c.class_type||'Functional';$('#cf-date').value=c.class_date||today();$('#cf-time').value=timeText(c.start_time||'08:00');$('#cf-duration').value=String(c.duration_minutes||60);$('#cf-coach').value=c.coach_id||'';$('#cf-cap').value=String(Math.min(10,Number(c.capacity||10)));$('#cf-cap').oninput=e=>e.target.value=Math.min(10,Math.max(1,Number(e.target.value||1)));$('#z33e-class-form').onsubmit=async e=>{e.preventDefault();const start=$('#cf-time').value;const dur=Number($('#cf-duration').value);const end=parseMinutes(start)+dur;const payload={class_type:$('#cf-type').value,class_date:$('#cf-date').value,start_time:start,end_time:String(Math.floor(end/60)).padStart(2,'0')+':'+String(end%60).padStart(2,'0'),duration_minutes:dur,coach_id:$('#cf-coach').value||null,capacity:Math.min(10,Math.max(1,Number($('#cf-cap').value||10))),status:'scheduled'};const r=id?await db.from('classes').update(payload).eq('id',id):await db.from('classes').insert(payload);if(r.error)return alert(r.error.message);closeDrawer();await loadData();agenda();};}
  async function cancelClass(id){if(!confirm('¿Cancelar esta clase?'))return;const r=await db.from('classes').update({status:'cancelled'}).eq('id',id);if(r.error)return alert(r.error.message);closeDrawer();await loadData();agenda();}

  function coachForm(id){const c=id?state.coaches.find(x=>x.id===id):{};openDrawer(id?'Editar coach':'Nuevo coach',`<form id="z33e-coach-form" class="z33e-form"><label>Nombre<input id="co-name" required></label><label>Especialidad<input id="co-specialty"></label><label>Foto URL<input id="co-photo"></label><label>Bio<textarea id="co-bio"></textarea></label><div class="z33e-actions"><button type="button" class="z33e-btn" onclick="closeDrawer()">Cancelar</button><button class="z33e-btn red">Guardar</button></div></form>`);$('#co-name').value=c.name||'';$('#co-specialty').value=c.specialty||'';$('#co-photo').value=c.photo_url||'';$('#co-bio').value=c.bio||'';$('#z33e-coach-form').onsubmit=async e=>{e.preventDefault();const payload={name:$('#co-name').value.trim(),specialty:$('#co-specialty').value.trim()||null,photo_url:$('#co-photo').value.trim()||null,bio:$('#co-bio').value.trim()||null,is_active:true,updated_at:new Date().toISOString()};const r=id?await db.from('coaches').update(payload).eq('id',id):await db.from('coaches').insert(payload);if(r.error)return alert(r.error.message);closeDrawer();await loadData();coaches()};}
  async function toggleCoach(id,active){const r=await db.from('coaches').update({is_active:active,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert(r.error.message);await loadData();coaches()}

  function paymentForm(id){const p=id?state.payments.find(x=>x.id===id):null;openDrawer(p?'Editar pago':'Registrar pago',`<form id="z33e-pay-form" class="z33e-form"><div class="z33e-row"><label>Cliente<select id="pf-client">${state.clients.map(c=>`<option value="${c.id}">${esc(c.full_name)} — ${esc(c.email||'')}</option>`).join('')}</select></label><label>Concepto<input id="pf-concept"></label></div><div class="z33e-row"><label>Monto<input id="pf-amount" type="number" min="0" step="0.01"></label><label>Fecha<input id="pf-date" type="date"></label></div><div class="z33e-row"><label>Método<select id="pf-method"><option>transferencia</option><option>ficha</option><option>online</option><option>efectivo</option><option>tarjeta</option></select></label><label>Estado<select id="pf-status"><option value="approved">Pagado</option><option value="pending">Pendiente</option><option value="rejected">Rechazado</option></select></label></div><label>Notas<textarea id="pf-notes"></textarea></label><div class="z33e-muted">Los clientes con Plan Fundadores pagan siempre $500.</div><div class="z33e-actions"><button type="button" class="z33e-btn" onclick="closeDrawer()">Cancelar</button><button class="z33e-btn red">Guardar</button>${p?`<button type="button" class="z33e-btn danger" onclick="deletePayment('${p.id}')">Eliminar</button>`:''}</div></form>`);$('#pf-client').value=p?.profile_id||state.clients[0]?.id||'';$('#pf-concept').value=p?.concept||p?.membership_plans?.name||'Mensualidad';$('#pf-amount').value=String(p?.amount??500);$('#pf-date').value=p?.payment_date||today();$('#pf-method').value=p?.method||'transferencia';$('#pf-status').value=p?.status||'approved';$('#pf-notes').value=p?.notes||'';const apply=()=>{const idc=$('#pf-client').value;const founder=state.memberships.some(m=>m.profile_id===idc&&m.status==='active'&&m.membership_plans?.is_founder_plan);$('#pf-amount').readOnly=founder;if(founder)$('#pf-amount').value='500'};$('#pf-client').onchange=apply;apply();$('#z33e-pay-form').onsubmit=async e=>{e.preventDefault();const idc=$('#pf-client').value;const founder=state.memberships.some(m=>m.profile_id===idc&&m.status==='active'&&m.membership_plans?.is_founder_plan);const payload={profile_id:idc,concept:$('#pf-concept').value.trim(),amount:founder?500:Number($('#pf-amount').value),payment_date:$('#pf-date').value,method:$('#pf-method').value,status:$('#pf-status').value,notes:$('#pf-notes').value.trim()||null};const r=id?await db.from('payments').update(payload).eq('id',id):await db.from('payments').insert(payload);if(r.error)return alert(r.error.message);closeDrawer();await loadData();finance('payments')};}
  async function deletePayment(id){if(!confirm('¿Eliminar este pago?'))return;const r=await db.from('payments').delete().eq('id',id);if(r.error)return alert(r.error.message);closeDrawer();await loadData();finance('payments')}
  function expenseForm(){openDrawer('Nuevo egreso',`<form id="z33e-exp-form" class="z33e-form"><div class="z33e-row"><label>Concepto<input id="ef-concept" required></label><label>Monto<input id="ef-amount" type="number" min="0" step="0.01" required></label></div><div class="z33e-row"><label>Fecha<input id="ef-date" type="date"></label><label>Categoría<input id="ef-cat" placeholder="Renta, insumos, servicios…"></label></div><label>Método<select id="ef-method"><option>transferencia</option><option>efectivo</option><option>tarjeta</option><option>online</option></select></label><label>Notas<textarea id="ef-notes"></textarea></label><div class="z33e-actions"><button type="button" class="z33e-btn" onclick="closeDrawer()">Cancelar</button><button class="z33e-btn red">Guardar egreso</button></div></form>`);$('#ef-date').value=today();$('#z33e-exp-form').onsubmit=async e=>{e.preventDefault();const r=await db.from('expenses').insert({concept:$('#ef-concept').value.trim(),amount:Number($('#ef-amount').value),expense_date:$('#ef-date').value,category:$('#ef-cat').value.trim()||null,method:$('#ef-method').value,notes:$('#ef-notes').value.trim()||null,created_by:state.profile.id});if(r.error)return alert(r.error.message);closeDrawer();await loadData();finance('reports')};}

  function planForm(id){const p=state.plans.find(x=>x.id===id);openDrawer('Editar plan',`<form id="z33e-plan-form" class="z33e-form"><label>Nombre<input id="pl-name"></label><label>Descripción<textarea id="pl-desc"></textarea></label><div class="z33e-row"><label>Precio<input id="pl-price" type="number" step="0.01"></label><label>Duración<input id="pl-days" type="number"></label></div><div class="z33e-muted">${p?.is_founder_plan?'Plan Fundadores: precio fijo de $500.':''}</div><div class="z33e-actions"><button type="button" class="z33e-btn" onclick="closeDrawer()">Cancelar</button><button class="z33e-btn red">Guardar</button></div></form>`);$('#pl-name').value=p?.name||'';$('#pl-desc').value=p?.description||'';$('#pl-price').value=p?.is_founder_plan?'500':String(p?.price||0);$('#pl-days').value=String(p?.duration_days||30);if(p?.is_founder_plan)$('#pl-price').readOnly=true;$('#z33e-plan-form').onsubmit=async e=>{e.preventDefault();const r=await db.from('membership_plans').update({name:$('#pl-name').value.trim(),description:$('#pl-desc').value.trim(),price:p?.is_founder_plan?500:Number($('#pl-price').value),duration_days:Number($('#pl-days').value||30)}).eq('id',id);if(r.error)return alert(r.error.message);closeDrawer();await loadData();finance('plans')};}

  function founderForm(id){const f=id?state.founders.find(x=>x.id===id):null;openDrawer(f?'Editar código':'Nuevo código',`<form id="z33e-founder-form" class="z33e-form"><label>Código<input id="fd-code" required></label><div class="z33e-muted">Un código activo da acceso al Plan Fundadores de $500.</div><div class="z33e-actions"><button type="button" class="z33e-btn" onclick="closeDrawer()">Cancelar</button><button class="z33e-btn red">Guardar</button>${f&&!f.used_by?`<button type="button" class="z33e-btn danger" onclick="deleteFounder('${f.id}')">Eliminar</button>`:''}</div></form>`);$('#fd-code').value=f?.code||'';$('#z33e-founder-form').onsubmit=async e=>{e.preventDefault();const code=$('#fd-code').value.trim().toUpperCase();const r=id?await db.from('founder_codes').update({code}).eq('id',id):await db.from('founder_codes').insert({code,is_active:true});if(r.error)return alert(r.error.message);closeDrawer();await loadData();finance('founders')};}
  async function toggleFounder(id,current){const r=await db.from('founder_codes').update({is_active:!current}).eq('id',id);if(r.error)return alert(r.error.message);await loadData();finance('founders')}
  async function deleteFounder(id){if(!confirm('¿Eliminar este código?'))return;const r=await db.from('founder_codes').delete().eq('id',id);if(r.error)return alert(r.error.message);closeDrawer();await loadData();finance('founders')}

  function landing(){const keys=Object.entries(state.site);setContent(`<div class="z33e-page"><div class="z33e-head"><div><div class="z33e-kicker">Contenido</div><div class="z33e-h2">Editar Landing</div><div class="z33e-sub">Aquí viven WOD, Leaderboard, Instagram, Comunidad y el resto del contenido del sitio.</div></div></div><div class="z33e-card"><div class="z33e-list">${keys.length?keys.map(([k,v])=>`<div class="z33e-item" style="align-items:flex-start"><div style="flex:1"><b>${esc(k)}</b><div class="z33e-muted">${esc(v)}</div></div><button class="z33e-btn" onclick="siteForm('${esc(k)}')">Editar</button></div>`).join(''):'<div class="z33e-empty">No hay contenido editable configurado.</div>'}</div></div></div>`, 'Editar Landing', currentDate());}
  function siteForm(key){openDrawer('Editar contenido',`<form id="z33e-site-form" class="z33e-form"><label>Clave<input value="${esc(key)}" readonly></label><label>Contenido<textarea id="site-value">${esc(state.site[key]||'')}</textarea></label><div class="z33e-actions"><button type="button" class="z33e-btn" onclick="closeDrawer()">Cancelar</button><button class="z33e-btn red">Guardar</button></div></form>`);$('#z33e-site-form').onsubmit=async e=>{e.preventDefault();const r=await db.from('site_content').upsert({key,value:$('#site-value').value,updated_at:new Date().toISOString()},{onConflict:'key'});if(r.error)return alert(r.error.message);closeDrawer();await loadData();landing()};}

  async function route(page){state.page=page;closeMenu();if(page==='dashboard')return dashboard();if(page==='clients')return clients();if(page==='agenda')return agenda(today());if(page==='coaches')return coaches();if(page==='finance')return finance(state.financeTab);if(page==='landing')return landing();}

  Object.assign(window,{route,finance,paymentForm,expenseForm,openClient,openClass,coachForm,toggleCoach,planForm,founderForm,toggleFounder,deleteFounder,siteForm,z33NewClass,classForm,cancelClass,closeDrawer,agenda});

  async function boot(){
    injectStyle();
    const {data:{session}}=await db.auth.getSession();
    if(!session)return;
    const {data:profile}=await db.from('profiles').select('*').eq('id',session.user.id).single();
    if(!profile||profile.role!=='admin')return;
    state.profile=profile;
    await loadData();
    shell('Dashboard',currentDate());
    route('dashboard');
    window.__z33ExactAdmin=true;
  }

  setTimeout(boot,1200);
  db.auth.onAuthStateChange((event)=>{ if(event==='SIGNED_IN') setTimeout(boot,250); });
})();