const SB_URL='https://ponhllwbvhtczaphfdgw.supabase.co';
const SB_KEY='sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
const sb=supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
window.__ZONA33_SB=sb; // cliente único de Supabase, compartido con admin.js
const app=document.querySelector('#app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'$'+Number(v||0).toLocaleString('es-MX');
const today=()=>new Date().toISOString().slice(0,10);
const dateText=v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'}):'—';
let me=null,profile=null,role='cliente';
// Este estado y router solo se usan para los roles "cliente" y "coach".
// El rol "admin" entrega el control por completo a admin.js (ver boot()).
const state={classes:[],reservations:[],memberships:[],payments:[],plans:[],coaches:[]};
function toast(msg){const x=document.querySelector('#toast');x.textContent=msg;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),3500)}
function auth(message=''){app.innerHTML=`<section class="auth"><div class="auth-card"><a class="brand" href="/"><img src="./assets/zona33-logo-portal.webp" alt="ZONA 33"><strong>ZONA 33</strong></a><div class="ey">Functional Club</div><h1>Tu portal.</h1><p class="muted">Reservas, membresía, pagos y gestión de ZONA 33 en un solo lugar.</p>${message?`<div class="notice"><b>Importante:</b> ${esc(message)}</div><br>`:''}<div class="form"><div class="field"><label>Correo</label><input id="loginEmail" type="email" autocomplete="email"></div><div class="field"><label>Contraseña</label><input id="loginPassword" type="password" autocomplete="current-password"></div><button class="btn red" onclick="login()">Iniciar sesión</button><button class="btn out" onclick="registerView()">Crear cuenta</button><button class="btn out" onclick="forgotPassword()">Olvidé mi contraseña</button></div></div></section>`}
function registerView(){app.innerHTML=`<section class="auth"><div class="auth-card"><a class="brand" href="/"><img src="./assets/zona33-logo-portal.webp" alt="ZONA 33"><strong>ZONA 33</strong></a><div class="ey">Nuevo miembro</div><h1>Únete.</h1><p class="muted">Crea tu cuenta. Te enviaremos un correo de confirmación.</p><div class="form"><div class="row"><div class="field"><label>Nombre completo</label><input id="rName" autocomplete="name"></div><div class="field"><label>Teléfono</label><input id="rPhone" autocomplete="tel"></div></div><div class="field"><label>Fecha de nacimiento</label><input id="rBirth" type="date"></div><div class="field"><label>Correo</label><input id="rEmail" type="email" autocomplete="email"></div><div class="field"><label>Contraseña</label><input id="rPassword" type="password" minlength="8" autocomplete="new-password"></div><div class="field"><label>Código de fundadores <span style="color:#777">(opcional)</span></label><input id="rFounderCode" autocomplete="off" autocapitalize="characters" placeholder="Ej. Z33-FOUND-001"><small class="muted">Si tienes un código, lo aplicaremos a tu cuenta al confirmar tu correo.</small></div><button class="btn red" onclick="register()">Crear cuenta</button><button class="btn out" onclick="auth()">Volver</button></div></div></section>`}
async function login(){const email=loginEmail.value.trim().toLowerCase(),password=loginPassword.value;if(!email||!password)return toast('Completa correo y contraseña.');const {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);boot()}
async function register(){const full_name=rName.value.trim(),phone=rPhone.value.trim(),birth_date=rBirth.value,email=rEmail.value.trim().toLowerCase(),password=rPassword.value,founder_code=(document.querySelector('#rFounderCode')?.value||'').trim().toUpperCase();if(!full_name||!phone||!birth_date||!email||password.length<8)return toast('Completa todos los datos.');const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name,phone,birth_date,role:'cliente',founder_code:founder_code||null,founder_code_redeemed:false},emailRedirectTo:location.href}});if(error)return toast(error.message);if(!data.session){auth(founder_code?'Cuenta creada. Confirma tu correo; al iniciar sesión aplicaremos tu código de fundadores.':'Cuenta creada. Revisa tu correo y confirma tu dirección antes de iniciar sesión.');return}boot()}
async function forgotPassword(){const email=prompt('Correo de tu cuenta ZONA 33');if(!email)return;const {error}=await sb.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:location.href});toast(error?'No pudimos enviar el enlace.':'Revisa tu correo para restablecer la contraseña.')}
async function logout(){await sb.auth.signOut();auth()}
async function redeemFounderCode(user){const code=String(user?.user_metadata?.founder_code||'').trim().toUpperCase();if(!code||user?.user_metadata?.founder_code_redeemed)return false;const {error}=await sb.rpc('claim_founder_code',{p_code:code});if(error){toast('Tu cuenta se creó, pero no pudimos aplicar el código: '+error.message);return false}const {error:metadataError}=await sb.auth.updateUser({data:{...user.user_metadata,founder_code_redeemed:true}});if(metadataError)console.warn('No se pudo marcar el código como aplicado.',metadataError.message);toast('Código de fundadores aplicado. Tu Plan Fundadores está activo.');return true}
async function boot(){
  const {data:{user}}=await sb.auth.getUser();
  if(!user){auth();return}
  me=user;
  const {data:p,error}=await sb.from('profiles').select('*').eq('id',user.id).single();
  if(error||!p){auth('Tu cuenta existe, pero todavía no hay un perfil disponible.');return}
  profile=p;role=p.role||'cliente';
  const redeemed=await redeemFounderCode(user);
  if(redeemed){const {data:{user:updatedUser}}=await sb.auth.getUser();if(updatedUser)me=updatedUser}
  if(role==='admin'){
    // Única fuente de verdad del panel admin: admin.js toma el control
    // completo de la pantalla a partir de aquí.
    if(!window.ZONA33_ADMIN){auth('El panel administrativo no pudo cargarse. Recarga la página.');return}
    await window.ZONA33_ADMIN.start(me,profile);
    return;
  }
  await refresh();renderShell();go('overview');
}
async function refresh(){const from=today();const [c,r,m,p,plans,coaches]=await Promise.all([sb.from('classes').select('*').eq('status','scheduled').gte('class_date',from).order('class_date').order('start_time'),sb.from('reservations').select('*,classes(class_date,start_time,class_type,capacity),coaches(name)').eq('profile_id',me.id).order('created_at',{ascending:false}),sb.from('memberships').select('*,membership_plans(name,price,is_founder_plan)').eq('profile_id',me.id).order('created_at',{ascending:false}),sb.from('payments').select('*,membership_plans(name)').eq('profile_id',me.id).order('created_at',{ascending:false}),sb.from('membership_plans').select('*').eq('is_active',true).order('sort_order'),sb.from('coaches').select('*').eq('is_active',true).order('name')]);const coachRows=coaches.data||[];const classRows=(c.data||[]).map(x=>({...x,coaches:coachRows.find(coach=>coach.id===x.coach_id)||null}));Object.assign(state,{classes:classRows,reservations:r.data||[],memberships:m.data||[],payments:p.data||[],plans:plans.data||[],coaches:coachRows})}
function nav(){if(role==='coach')return[['overview','Dashboard'],['agenda','Agenda'],['coachprofile','Mi perfil']];return[['overview','Dashboard'],['book','Reservar'],['reservations','Mis reservas'],['membership','Membresía'],['payments','Pagos'],['account','Mi perfil']]}
function renderShell(){app.innerHTML=`<div class="shell"><aside class="side"><a class="brand" href="/"><img src="./assets/zona33-logo-portal.webp" alt="ZONA 33"><strong>ZONA 33</strong></a><div class="role">${esc(role)} · portal</div><nav class="nav" id="nav">${nav().map(([k,v])=>`<button data-page="${k}">${v}</button>`).join('')}</nav><div class="sidefoot">ZONA 33 FUNCTIONAL CLUB<br>Portal operativo</div></aside><main class="main"><header class="top"><div><div class="ey">ZONA 33</div><h1 id="pageTitle">Dashboard</h1></div><div class="top-actions"><span class="pill ok">Conectado</span><button class="btn out" onclick="location.href='/'">Sitio</button><button class="btn danger" onclick="logout()">Salir</button></div></header><section class="content" id="content"></section><div class="mobilebar"><button class="btn red" onclick="go('overview')">Inicio</button><button class="btn" onclick="location.href='/'">Sitio</button><button class="btn danger" onclick="logout()">Salir</button></div></main></div>`;document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page))}
const labels={overview:'Dashboard',book:'Reservar',reservations:'Mis reservas',membership:'Membresía',payments:'Pagos',account:'Mi perfil',agenda:'Agenda',coachprofile:'Mi perfil'};
function go(page){document.querySelector('#pageTitle').textContent=labels[page]||'Portal';document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const c=document.querySelector('#content');if(page==='overview')role==='coach'?coachHome(c):clientHome(c);else if(page==='book')book(c);else if(page==='reservations')clientReservations(c);else if(page==='membership')clientMembership(c);else if(page==='payments')clientPayments(c);else if(page==='account')clientAccount(c);else if(page==='agenda')coachAgenda(c);else if(page==='coachprofile')coachProfile(c)}
function clientHome(c){const active=state.memberships.find(x=>x.status==='active'&&x.end_date>=today());const next=state.reservations.filter(x=>x.status==='reserved').slice(0,4);c.innerHTML=`<div class="hero"><div class="ey">Bienvenida</div><h2>Hola, <span>${esc((profile.full_name||'Atleta').split(' ')[0])}.</span></h2><p class="muted">Tu entrenamiento, reservas y membresía en un solo lugar.</p></div><div class="grid grid3"><div class="card stat"><small>Membresía</small><b>${esc(active?.membership_plans?.name||'Sin plan')}</b><span class="pill ${active?'ok':'warn'}">${active?'Activa':'Pendiente'}</span></div><div class="card stat"><small>Próximas reservas</small><b>${next.length}</b></div><div class="card stat"><small>Pagos registrados</small><b>${state.payments.length}</b></div></div><br><div class="grid grid2"><div class="card"><div class="ey">Entrenamiento</div><h2>Reserva tu próxima clase.</h2><p class="muted">Elige día y horario y aparta tu lugar.</p><button class="btn red" onclick="go('book')">Ver horarios</button></div><div class="card"><div class="ey">Membresía</div><h2>${esc(active?dateText(active.end_date):'Sin vigencia')}</h2><button class="btn out" onclick="go('membership')">Ver membresía</button></div></div><br><div class="card"><div class="ey">Agenda</div><h2>Mis próximas reservas.</h2><div class="list">${next.length?next.map(x=>`<div class="item"><div><b>${esc(x.classes?.class_type||'Functional')}</b><small>${esc(dateText(x.classes?.class_date))} · ${esc(String(x.classes?.start_time||'').slice(0,5))} · ${esc(x.coaches?.name||'Coach Z33')}</small></div><span class="pill ok">Reservada</span></div>`).join(''):'<div class="empty">No tienes reservas futuras.</div>'}</div></div>`}
function book(c){const rows=state.classes.slice(0,30);c.innerHTML=`<div class="hero"><div class="ey">Horarios</div><h2>Elige tu <span>clase.</span></h2><p class="muted">Las reservas se guardan directamente en ZONA 33.</p></div><div class="card"><div class="list">${rows.length?rows.map(x=>{const mine=state.reservations.some(r=>r.class_id===x.id&&r.status==='reserved');return `<div class="item"><div><b>${esc(String(x.start_time).slice(0,5))} · ${esc(x.class_type)}</b><small>${esc(dateText(x.class_date))} · ${esc(x.coaches?.name||'Coach Z33')} · Cupo ${esc(x.capacity)}</small></div><button class="btn ${mine?'out':'red'}" ${mine?'disabled':`onclick="reserve('${x.id}')"`}>${mine?'RESERVADA':'RESERVAR'}</button></div>`}).join(''):'<div class="empty">No hay clases disponibles.</div>'}</div></div>`}
async function reserve(id){const {error}=await sb.rpc('reserve_class',{p_class_id:id});if(error)return toast(error.message);await refresh();toast('Clase reservada.');go('reservations')}
async function cancelReservation(id){if(!confirm('¿Cancelar esta reserva?'))return;const {error}=await sb.from('reservations').update({status:'cancelled',cancelled_at:new Date().toISOString()}).eq('id',id).eq('profile_id',me.id);if(error)return toast(error.message);await refresh();toast('Reserva cancelada.');go('reservations')}
function clientReservations(c){c.innerHTML=`<div class="hero"><div class="ey">Cliente</div><h2>Mis <span>reservas.</span></h2></div><div class="card"><div class="list">${state.reservations.length?state.reservations.map(x=>`<div class="item"><div><b>${esc(x.classes?.class_type||'Functional')}</b><small>${esc(dateText(x.classes?.class_date))} · ${esc(String(x.classes?.start_time||'').slice(0,5))} · ${esc(x.coaches?.name||'Coach Z33')}</small></div><div class="actions"><span class="pill ${x.status==='reserved'?'ok':'bad'}">${esc(x.status)}</span>${x.status==='reserved'?`<button class="btn danger" onclick="cancelReservation('${x.id}')">Cancelar</button>`:''}</div></div>`).join(''):'<div class="empty">Aún no tienes reservas.</div>'}</div></div>`}
function clientMembership(c){const active=state.memberships.find(x=>x.status==='active'&&x.end_date>=today());const pending=state.memberships.find(x=>x.status==='pending');c.innerHTML=`<div class="hero"><div class="ey">Membresía</div><h2>Mi <span>plan.</span></h2></div><div class="grid grid2">${active?`<div class="card"><div class="ey">Actual</div><h2>${esc(active.membership_plans?.name||'Membresía')}</h2><p class="muted">${esc(active.start_date)} → ${esc(active.end_date)}</p><span class="pill ok">${esc(active.status)}</span></div>`:`<div class="card"><h2>${pending?'Solicitud en revisión.':'Sin membresía activa.'}</h2><p class="muted">${pending?'Tu solicitud está pendiente de confirmación.':'Elige un plan para comenzar.'}</p></div>`}<div class="card"><div class="ey">Planes disponibles</div><div class="list">${state.plans.map(p=>`<div class="item"><div><b>${esc(p.name)}</b><small>${esc(p.description||'')}</small></div><div style="display:grid;gap:8px;justify-items:end"><strong>${money(p.price)}</strong>${p.is_founder_plan?`<span class="pill warn">Solo con código fundador</span>`:`<button class="btn red" onclick="requestMembership('${p.id}')">${pending?'Solicitud pendiente':'Elegir plan'}</button>`}</div></div>`).join('')}</div></div></div>`}
async function requestMembership(planId){const active=state.memberships.find(x=>x.status==='active'&&x.end_date>=today());const pending=state.memberships.find(x=>x.status==='pending');if(active)return toast('Ya tienes una membresía activa.');if(pending)return toast('Ya tienes una solicitud de membresía pendiente.');const {error}=await sb.rpc('request_membership',{p_plan_id:planId});if(error)return toast(error.message);await refresh();toast('Solicitud de membresía registrada. Te contactaremos para confirmar tu pago.');go('membership')}
function clientPayments(c){c.innerHTML=`<div class="hero"><div class="ey">Pagos</div><h2>Mi <span>historial.</span></h2></div><div class="card"><div class="list">${state.payments.length?state.payments.map(x=>`<div class="item"><div><b>${esc(x.membership_plans?.name||'Pago')}</b><small>${esc(new Date(x.created_at).toLocaleDateString('es-MX'))} · ${esc(x.method)}</small></div><div><strong>${money(x.amount)}</strong><span class="pill ${x.status==='approved'?'ok':'warn'}">${esc(x.status)}</span></div></div>`).join(''):'<div class="empty">Aún no hay pagos registrados.</div>'}</div></div>`}
function clientAccount(c){c.innerHTML=`<div class="hero"><div class="ey">Perfil</div><h2>Mi <span>cuenta.</span></h2></div><div class="card"><form class="form" onsubmit="saveAccount(event)"><div class="field"><label>Nombre completo</label><input id="accName" value="${esc(profile.full_name)}" required></div><div class="field"><label>Teléfono</label><input id="accPhone" value="${esc(profile.phone||'')}"></div><div class="field"><label>Fecha de nacimiento</label><input id="accBirth" type="date" value="${esc(profile.birth_date||'')}"></div><div class="field"><label>Correo</label><input value="${esc(profile.email||me.email)}" disabled></div><button class="btn red">Guardar cambios</button></form></div>`}
async function saveAccount(e){e.preventDefault();const {data,error}=await sb.from('profiles').update({full_name:accName.value,phone:accPhone.value,birth_date:accBirth.value,updated_at:new Date().toISOString()}).eq('id',me.id).select().single();if(error)return toast(error.message);profile=data;toast('Perfil actualizado.');go('account')}
function coachHome(c){c.innerHTML=`<div class="hero"><div class="ey">Coach</div><h2>Hola, <span>${esc((profile.full_name||'Coach').split(' ')[0])}.</span></h2></div><div class="grid grid3"><div class="card stat"><small>Clases próximas</small><b>${state.classes.length}</b></div><div class="card stat"><small>Hoy</small><b>${state.classes.filter(x=>x.class_date===today()).length}</b></div><div class="card stat"><small>Perfil</small><b>Activo</b></div></div><br><div class="card"><button class="btn red" onclick="go('agenda')">Ver agenda</button></div>`}
function coachAgenda(c){const mine=state.classes.filter(x=>x.coach_id===profile.id);c.innerHTML=`<div class="hero"><div class="ey">Agenda</div><h2>Mis <span>clases.</span></h2></div><div class="card"><div class="list">${mine.length?mine.map(x=>`<div class="item"><div><b>${esc(dateText(x.class_date))} · ${esc(String(x.start_time).slice(0,5))}</b><small>${esc(x.class_type)} · Cupo ${esc(x.capacity)}</small></div><span class="pill ${x.status==='scheduled'?'ok':'bad'}">${esc(x.status)}</span></div>`).join(''):'<div class="empty">No hay clases asignadas.</div>'}</div></div>`}
function coachProfile(c){c.innerHTML=`<div class="hero"><div class="ey">Coach</div><h2>Mi <span>perfil.</span></h2></div><div class="card"><form class="form" onsubmit="saveCoachProfile(event)"><div class="field"><label>Nombre</label><input id="cpName" value="${esc(profile.full_name)}" required></div><div class="field"><label>Correo</label><input value="${esc(profile.email||me.email)}" disabled></div><button class="btn red">Guardar</button></form></div>`}
async function saveCoachProfile(e){e.preventDefault();const {data,error}=await sb.from('profiles').update({full_name:cpName.value,updated_at:new Date().toISOString()}).eq('id',me.id).select().single();if(error)return toast(error.message);profile=data;toast('Perfil actualizado.')}
boot();
