(()=>{'use strict';
const U='https://ponhllwbvhtczaphfdgw.supabase.co',K='sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
const api=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const getVal=(root,sel)=>root.querySelector(sel)?.value?.trim()||'';
const toast=m=>window.toast?window.toast(m):alert(m);
async function saveSite(key,value){const {data:{user}}=await api.auth.getUser();const {error}=await api.from('site_content').upsert({key,value,is_public:true,updated_by:user?.id||null,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error;}
async function uploadImage(){const input=document.createElement('input');input.type='file';input.accept='image/*';return new Promise((resolve,reject)=>{input.onchange=async()=>{const f=input.files?.[0];if(!f)return resolve('');try{if(f.size>8*1024*1024)throw new Error('La imagen debe pesar menos de 8 MB.');const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`landing/${Date.now()}-${crypto.randomUUID()}.${ext}`;const q=await api.storage.from('site-media').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type||'image/jpeg'});if(q.error)throw q.error;resolve(api.storage.from('site-media').getPublicUrl(path).data.publicUrl)}catch(e){reject(e)}};input.click()})}
const slots=[
 ['HERO','Portada'],
 ['WOD','Después del WOD'],
 ['EQUIPO','Equipo'],
 ['COMUNIDAD','Comunidad'],
 ['CELEBRAMOS','Celebramos'],
];
async function loadGallery(){const {data}=await api.from('site_content').select('value').eq('key','landing_gallery').maybeSingle();return Array.isArray(data?.value?.images)?data.value.images:[]}
async function loadPeople(){const r=await api.from('landing_people').select('*').order('position').order('created_at');if(r.error)throw r.error;return r.data||[]}
function personCard(x){return `<div class='card z12-person' data-id='${esc(x?.id||'')}'><div class='ey'>${x?.is_published===false?'OCULTO':'VISIBLE EN LANDING'} · #${x?.position||1}</div><div class='row'><div class='field'><label>Nombre</label><input class='z12-name' value='${esc(x?.name||'')}'></div><div class='field'><label>Resultado</label><input class='z12-result' value='${esc(x?.result||'')}' placeholder='Ej. -8 kg / 12 semanas'></div></div><div class='row'><div class='field'><label>Categoría</label><input class='z12-cat' value='${esc(x?.category||'')}' placeholder='Fuerza / Condición'></div><div class='field'><label>Posición</label><input class='z12-pos' type='number' min='1' value='${x?.position||1}'></div></div><div class='row'><div class='field'><label>WOD / contexto</label><input class='z12-wod' value='${esc(x?.wod_name||'')}' placeholder='Opcional'></div><div class='field'><label>Visible</label><select class='z12-pub'><option value='true' ${x?.is_published!==false?'selected':''}>Sí</option><option value='false' ${x?.is_published===false?'selected':''}>No</option></select></div></div><div class='field'><label>Descripción</label><textarea class='z12-desc' placeholder='Historia, progreso o frase de la persona'>${esc(x?.description||'')}</textarea></div><div class='field'><label>Foto</label><div class='row'><input class='z12-photo' value='${esc(x?.photo_url||'')}' placeholder='https://...'><button class='btn out z12-upload'>Subir foto</button></div></div><div class='z12-preview-wrap'>${x?.photo_url?`<img class='z12-preview' src='${esc(x.photo_url)}' alt='${esc(x.name||'Persona real')}' style='width:120px;height:120px;border-radius:12px;object-fit:cover;margin-top:6px'>`:''}</div><div class='actions' style='margin-top:10px'><button class='btn red z12-save'>Guardar</button>${x?.id?`<button class='btn danger z12-delete'>Eliminar</button>`:''}</div></div>`}
async function replaceLandingEditor(c){
 const old=[...c.querySelectorAll('.card')].find(el=>/Fotos del landing/i.test(el.textContent||''));
 if(old)old.remove();
 const gallery=await loadGallery();
 const shell=document.createElement('div');shell.className='grid z12-landing-admin';
 if(!document.getElementById('z12-compact-style')){const style=document.createElement('style');style.id='z12-compact-style';style.textContent=`.z12-landing-admin{gap:14px}.z12-gallery-card{padding:16px}.z12-gallery-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.z12-slot{padding:12px;border:1px solid #262626;border-radius:10px;background:#0b0b0b}.z12-slot-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}.z12-slot-name{font-size:13px;font-weight:900}.z12-slot .field{gap:5px}.z12-slot .field label{font-size:8px}.z12-slot .z12-gup{width:100%;margin-top:6px;min-height:38px}.z12-gprev{width:100%;height:120px;object-fit:cover;border-radius:7px;margin-top:8px;border:1px solid #242424;background:#111}.z12-people-admin{padding:16px}.z12-person{padding:14px}.z12-person .row{gap:10px}.z12-person .field label{font-size:8px}.z12-person textarea{min-height:90px}@media(max-width:800px){.z12-gallery-grid{grid-template-columns:1fr}}`;document.head.appendChild(style)}
 const g=document.createElement('div');g.className='card z12-gallery-card';g.innerHTML=`<div class='ey'>Galería</div><h2>Fotos del landing.</h2><p class='muted'>Cada foto está identificada por su sección. Puedes pegar una URL o subir el archivo.</p><div class='grid z12-gallery-grid' id='z12gallery'></div><div class='actions' style='margin-top:12px'><button class='btn red' id='z12saveGallery'>Guardar galería</button></div>`;
 const gl=g.querySelector('#z12gallery');
 slots.forEach((s,i)=>{const card=document.createElement('div');card.className='z12-slot';card.innerHTML=`<div class='z12-slot-head'><span class='ey'>${esc(s[0])}</span><span class='z12-slot-name'>${esc(s[1])}</span></div><div class='field'><label>Imagen</label><input class='z12-gurl' data-index='${i}' value='${esc(gallery[i]||'')}' placeholder='Pega URL de imagen'><button class='btn out z12-gup' data-index='${i}'>Subir archivo</button></div><img class='z12-gprev' src='${esc(gallery[i]||'')}' alt='' style='${gallery[i]?'':'display:none'}'>`;gl.appendChild(card)});
 g.querySelector('#z12saveGallery').onclick=async()=>{try{const imgs=[...g.querySelectorAll('.z12-gurl')].sort((a,b)=>Number(a.dataset.index)-Number(b.dataset.index)).map(x=>x.value.trim());await saveSite('landing_gallery',{images:imgs});toast('Galería actualizada.');}catch(e){toast('No se pudo guardar la galería: '+e.message)}};
 g.querySelectorAll('.z12-gup').forEach(b=>b.onclick=async()=>{try{const u=await uploadImage();if(!u)return;const i=b.dataset.index,inp=g.querySelector(`.z12-gurl[data-index='${i}']`);inp.value=u;const img=b.parentElement.querySelector('.z12-gprev');img.src=u;img.style.display='block'}catch(e){toast('No se pudo subir la imagen: '+e.message)}});
 shell.appendChild(g);
 const pbox=document.createElement('div');pbox.className='card z12-people-admin';pbox.innerHTML=`<div class='ey'>Personas reales</div><h2>Resultados del mes.</h2><p class='muted'>Esta sección es independiente del Leaderboard. Son personas que quieres destacar en el landing, con su propia foto, historia y resultado.</p><div class='actions' style='margin:12px 0'><button class='btn red' id='z12add'>+ Agregar persona</button></div><div class='grid' id='z12people'></div>`;
 const people=await loadPeople();const list=pbox.querySelector('#z12people');const bind=()=>{list.querySelectorAll('.z12-upload').forEach(b=>b.onclick=async()=>{try{const u=await uploadImage();if(!u)return;const root=b.closest('.z12-person');root.querySelector('.z12-photo').value=u;let p=root.querySelector('.z12-preview');if(!p){p=document.createElement('img');p.className='z12-preview';p.style.cssText='width:120px;height:120px;border-radius:12px;object-fit:cover;margin-top:6px';root.querySelector('.z12-preview-wrap').appendChild(p)}p.src=u}catch(e){toast('No se pudo subir la foto: '+e.message)}});list.querySelectorAll('.z12-save').forEach(b=>b.onclick=async()=>{const r=b.closest('.z12-person'),id=r.dataset.id,p={name:getVal(r,'.z12-name'),result:getVal(r,'.z12-result')||null,category:getVal(r,'.z12-cat')||null,position:Number(getVal(r,'.z12-pos')||1),wod_name:getVal(r,'.z12-wod')||null,description:getVal(r,'.z12-desc')||null,photo_url:getVal(r,'.z12-photo')||null,is_published:r.querySelector('.z12-pub')?.value==='true',updated_at:new Date().toISOString()};if(!p.name)return toast('Escribe el nombre de la persona.');const q=id?await api.from('landing_people').update(p).eq('id',id):await api.from('landing_people').insert(p);if(q.error)return toast('No se pudo guardar: '+q.error.message);toast('Persona guardada.');window.go('site')});list.querySelectorAll('.z12-delete').forEach(b=>b.onclick=async()=>{const r=b.closest('.z12-person');if(!confirm('¿Eliminar esta persona del landing?'))return;const q=await api.from('landing_people').delete().eq('id',r.dataset.id);if(q.error)return toast(q.error.message);toast('Persona eliminada.');window.go('site')})};const draw=()=>{list.innerHTML=people.map(personCard).join('')||'<div class="empty">Todavía no hay personas destacadas.</div>';bind()};pbox.querySelector('#z12add').onclick=()=>{people.unshift({id:'',name:'',result:'',category:'',position:1,wod_name:'',description:'',photo_url:'',is_published:true});draw()};draw();shell.appendChild(pbox);c.appendChild(shell);
}
async function install(){for(let i=0;i<80;i++){if(typeof window.adminSite==='function'){if(window.__Z12_SITE)return;window.__Z12_SITE=true;const original=window.adminSite;window.adminSite=async c=>{await original(c);await replaceLandingEditor(c)};return}await new Promise(r=>setTimeout(r,250))}}
install();
})();
