(()=>{'use strict';
const U='https://ponhllwbvhtczaphfdgw.supabase.co',K='sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
const api=window.sb||supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const toast=m=>window.toast?window.toast(m):alert(m);
const val=(r,s)=>r.querySelector(s)?.value?.trim()||'';
async function upload(filePathPrefix){const input=document.createElement('input');input.type='file';input.accept='image/*';return new Promise((resolve,reject)=>{input.onchange=async()=>{const f=input.files?.[0];if(!f)return resolve('');try{if(f.size>8*1024*1024)throw new Error('La foto debe pesar menos de 8 MB.');const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${filePathPrefix}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const q=await api.storage.from('site-media').upload(path,f,{upsert:false,contentType:f.type||'image/jpeg',cacheControl:'3600'});if(q.error)throw q.error;resolve(api.storage.from('site-media').getPublicUrl(path).data.publicUrl)}catch(e){reject(e)}};input.click()})}
async function getCoaches(){const r=await api.from('coaches').select('*').order('name');if(r.error)throw r.error;return r.data||[]}
function coachCard(x){return `<div class='card z14-coach' data-id='${esc(x.id||'')}' style='padding:14px'><div class='ey'>${x.is_active?'ACTIVO':'INACTIVO'}</div><div class='row'><div class='field'><label>Nombre</label><input class='z14-name' value='${esc(x.name||'')}'></div><div class='field'><label>Especialidad</label><input class='z14-spec' value='${esc(x.specialty||'')}'></div></div><div class='field'><label>Bio</label><textarea class='z14-bio' placeholder='Descripción breve del coach'>${esc(x.bio||'')}</textarea></div><div class='field'><label>Foto del coach</label><div class='row'><input class='z14-photo' value='${esc(x.photo_url||'')}' placeholder='URL opcional'><button type='button' class='btn out z14-upload'>Subir foto</button></div></div><div class='z14-preview' style='min-height:8px'>${x.photo_url?`<img src='${esc(x.photo_url)}' alt='${esc(x.name||'Coach')}' style='width:100px;height:100px;object-fit:cover;border-radius:12px;margin-top:6px'>`:''}</div><div class='field'><label>Estado</label><select class='z14-active'><option value='true' ${x.is_active!==false?'selected':''}>Activo</option><option value='false' ${x.is_active===false?'selected':''}>Inactivo</option></select></div><button type='button' class='btn red z14-save'>Guardar coach</button></div>`}
async function renderCoaches(c){const rows=await getCoaches();c.innerHTML=`<div class='hero'><div class='ey'>Equipo</div><h2>Coaches.</h2><p class='muted'>Edita la información del equipo y sube sus fotos directamente desde tu computadora.</p><button class='btn red' id='z14add'>+ Agregar coach</button></div><div class='grid grid2' id='z14list'>${rows.map(coachCard).join('')}</div>`;const list=c.querySelector('#z14list');const bind=()=>{list.querySelectorAll('.z14-upload').forEach(b=>b.onclick=async()=>{try{const u=await upload('coaches');if(!u)return;const r=b.closest('.z14-coach');r.querySelector('.z14-photo').value=u;r.querySelector('.z14-preview').innerHTML=`<img src='${esc(u)}' alt='Coach' style='width:100px;height:100px;object-fit:cover;border-radius:12px;margin-top:6px'>`}catch(e){toast('No se pudo subir la foto: '+e.message)}});list.querySelectorAll('.z14-save').forEach(b=>b.onclick=async()=>{const r=b.closest('.z14-coach'),id=r.dataset.id,p={name:val(r,'.z14-name'),specialty:val(r,'.z14-spec')||null,bio:val(r,'.z14-bio')||null,photo_url:val(r,'.z14-photo')||null,is_active:r.querySelector('.z14-active').value==='true',updated_at:new Date().toISOString()};if(!p.name)return toast('Escribe el nombre del coach.');const q=id?await api.from('coaches').update(p).eq('id',id):await api.from('coaches').insert(p);if(q.error)return toast('No se pudo guardar: '+q.error.message);toast('Coach guardado.');renderCoaches(c)} )};bind();c.querySelector('#z14add').onclick=()=>{const wrap=c.querySelector('#z14list');const el=document.createElement('div');el.innerHTML=coachCard({id:'',name:'',specialty:'',bio:'',photo_url:'',is_active:true});wrap.prepend(el.firstElementChild);bind()}}
async function contactEditor(c){const r=await api.from('site_content').select('value').eq('key','contact').maybeSingle();const d=r.data?.value||{};const box=document.createElement('div');box.className='card z14-contact';box.innerHTML=`<div class='ey'>Contacto</div><h2>Información de contacto.</h2><p class='muted'>Estos datos se pueden mostrar en el landing.</p><div class='row'><div class='field'><label>Teléfono / WhatsApp</label><input id='z14phone' value='${esc(d.phone||'')}'></div><div class='field'><label>Correo</label><input id='z14email' type='email' value='${esc(d.email||'')}' placeholder='hola@zona33.com'></div></div><div class='row'><div class='field'><label>Instagram</label><input id='z14ig' value='${esc(d.instagram||'')}'></div><div class='field'><label>Dirección</label><input id='z14addr' value='${esc(d.address||'')}'></div></div><button class='btn red' id='z14saveContact'>Guardar contacto</button>`;c.appendChild(box);box.querySelector('#z14saveContact').onclick=async()=>{const {data:{user}}=await api.auth.getUser();const value={phone:box.querySelector('#z14phone').value.trim(),email:box.querySelector('#z14email').value.trim(),instagram:box.querySelector('#z14ig').value.trim(),address:box.querySelector('#z14addr').value.trim()};const q=await api.from('site_content').upsert({key:'contact',value,is_public:true,updated_by:user?.id||null,updated_at:new Date().toISOString()},{onConflict:'key'});if(q.error)return toast('No se pudo guardar: '+q.error.message);toast('Contacto actualizado.')}}
async function install(){for(let i=0;i<80;i++){if(typeof window.adminCoaches==='function'&&typeof window.adminSite==='function'){if(window.__Z14)return;window.__Z14=true;window.adminCoaches=renderCoaches;const originalSite=window.adminSite;window.adminSite=async c=>{await originalSite(c);await contactEditor(c)};return}await new Promise(r=>setTimeout(r,250))}}install();
})();
