(()=>{
'use strict';
const U='https://ponhllwbvhtczaphfdgw.supabase.co',K='sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
const api=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const toast=m=>window.toast?window.toast(m):alert(m);
async function uploadPhoto(){const input=document.createElement('input');input.type='file';input.accept='image/*';return new Promise((resolve,reject)=>{input.onchange=async()=>{const f=input.files?.[0];if(!f)return resolve('');try{if(f.size>8*1024*1024)throw new Error('La foto debe pesar menos de 8 MB.');const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`landing/people-${Date.now()}-${crypto.randomUUID()}.${ext}`;const q=await api.storage.from('site-media').upload(path,f,{upsert:false,contentType:f.type||'image/jpeg',cacheControl:'3600'});if(q.error)throw q.error;resolve(api.storage.from('site-media').getPublicUrl(path).data.publicUrl)}catch(e){reject(e)}};input.click()})}
async function getPeople(){const r=await api.from('leaderboard_entries').select('id,athlete_name,category,position,wod_name,score,photo_url,is_published,created_at').order('position').order('created_at');if(r.error)throw r.error;return r.data||[]}
function card(x){return `<div class='card z11-person' data-id='${x.id||''}'><div class='ey'>${x?.is_published===false?'OCULTO':'VISIBLE EN LANDING'} · #${x?.position||1}</div><div class='row'><div class='field'><label>Nombre</label><input class='z11-name' value='${esc(x?.athlete_name||'')}'></div><div class='field'><label>Resultado</label><input class='z11-score' value='${esc(x?.score||'')}' placeholder='Ej. 10:42 / 120 kg'></div></div><div class='row'><div class='field'><label>Categoría</label><input class='z11-cat' value='${esc(x?.category||'')}' placeholder='RX / Scaled'></div><div class='field'><label>Posición</label><input class='z11-pos' type='number' min='1' value='${x?.position||1}'></div></div><div class='row'><div class='field'><label>WOD</label><input class='z11-wod' value='${esc(x?.wod_name||'')}' placeholder='Nombre del WOD'></div><div class='field'><label>Visible</label><select class='z11-pub'><option value='true' ${x?.is_published!==false?'selected':''}>Sí</option><option value='false' ${x?.is_published===false?'selected':''}>No</option></select></div></div><div class='field'><label>Foto de la persona</label><input class='z11-photo' value='${esc(x?.photo_url||'')}' placeholder='Pega URL o sube una foto'><button class='btn out z11-upload'>Subir foto</button></div>${x?.photo_url?`<img class='z11-preview' src='${esc(x.photo_url)}' alt='${esc(x.athlete_name||'Persona real')}' style='width:120px;height:120px;border-radius:12px;object-fit:cover;margin-top:4px'>`:''}<div class='actions' style='margin-top:10px'><button class='btn red z11-save'>Guardar</button>${x?.id?`<button class='btn danger z11-delete'>Eliminar</button>`:''}</div></div>`}
async function install(){for(let i=0;i<80;i++){if(typeof window.adminSite==='function'){if(window.__Z11_SITE)return;window.__Z11_SITE=true;const original=window.adminSite;window.adminSite=async function(c){await original(c);const old=[...c.querySelectorAll('.card')].find(el=>/Fotos del landing/i.test(el.textContent||''));if(old)old.remove();const box=document.createElement('div');box.className='card z11-people-editor';box.innerHTML=`<div class='ey'>Personas reales</div><h2>Resultados del mes.</h2><p class='muted'>Estas personas aparecerán en la sección de resultados del landing. Sube su foto y completa sus datos.</p><div class='actions' style='margin:12px 0'><button class='btn red' id='z11add'>+ Agregar persona</button></div><div class='grid' id='z11people'></div>`;c.appendChild(box);let rows=await getPeople();const list=box.querySelector('#z11people');const bind=()=>{list.querySelectorAll('.z11-upload').forEach(b=>b.onclick=async()=>{try{const u=await uploadPhoto();if(!u)return;const root=b.closest('.z11-person');root.querySelector('.z11-photo').value=u;let p=root.querySelector('.z11-preview');if(!p){p=document.createElement('img');p.className='z11-preview';p.style.cssText='width:120px;height:120px;border-radius:12px;object-fit:cover;margin-top:4px';root.insertBefore(p,root.querySelector('.actions'));}p.src=u;}catch(e){toast('No se pudo subir la foto: '+e.message)}});list.querySelectorAll('.z11-save').forEach(b=>b.onclick=async()=>{const root=b.closest('.z11-person'),id=root.dataset.id,v=s=>root.querySelector(s)?.value?.trim()||'';const p={athlete_name:v('.z11-name'),score:v('.z11-score')||null,category:v('.z11-cat')||null,position:Number(v('.z11-pos')||1),wod_name:v('.z11-wod')||null,is_published:v('.z11-pub')==='true',photo_url:v('.z11-photo')||null,updated_at:new Date().toISOString()};const r=id?await api.from('leaderboard_entries').update(p).eq('id',id):await api.from('leaderboard_entries').insert(p);if(r.error)return toast('No se pudo guardar: '+r.error.message);toast('Persona guardada.');window.go('site')});list.querySelectorAll('.z11-delete').forEach(b=>b.onclick=async()=>{const root=b.closest('.z11-person');if(!confirm('¿Eliminar esta persona?'))return;const r=await api.from('leaderboard_entries').delete().eq('id',root.dataset.id);if(r.error)return toast(r.error.message);toast('Persona eliminada.');window.go('site')})};const draw=()=>{list.innerHTML=rows.map(card).join('')||'<div class="empty">No hay personas agregadas todavía.</div>';bind()};box.querySelector('#z11add').onclick=()=>{rows=[{id:'',athlete_name:'',category:'',position:1,wod_name:'',score:'',photo_url:'',is_published:true},...rows];draw()};draw();return}await new Promise(r=>setTimeout(r,250))}}
install();
})();
