(()=>{
'use strict';
const U='https://ponhllwbvhtczaphfdgw.supabase.co';
const K='sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
const api4=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const q=id=>document.querySelector('#'+id)?.value?.trim()||'';
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const getUser=async()=> (await api4.auth.getUser()).data.user;
async function save4(key,value){const user=await getUser();const {error}=await api4.from('site_content').upsert({key,value,is_public:true,updated_by:user?.id||null,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error;}
const defaults={brand:{logo_url:'',logoUrl:'',instagram:'@zona33functionalclub'},hero:{title:'SER TU MEJOR VERSIÓN',headline:'SER TU MEJOR VERSIÓN',copy:'Clases dirigidas por entrenadores. Una comunidad que se apoya mutuamente, día tras día.',subheadline:'Aquí empieza la fortaleza',image_url:'',imageUrl:''},contact:{phone:'2229195074',address:'C. Tlaxcala 1030-local 33, 72682 San Francisco Ocotlán, Pue.'},community:{headline:'MORE THAN A GYM',instagram:'@zona33functionalclub'},landing_gallery:{images:[]}};
const isAdmin=()=>/admin/i.test(document.querySelector('.role')?.textContent||'');
function ensureLandingNav(){if(!isAdmin())return;const nav=document.querySelector('#nav');if(!nav)return;if(!nav.querySelector('[data-page="site"]')){const b=document.createElement('button');b.dataset.page='site';b.textContent='Landing';b.onclick=()=>window.go('site');nav.appendChild(b)}}
new MutationObserver(ensureLandingNav).observe(document.body,{childList:true,subtree:true});setTimeout(ensureLandingNav,250);
function galleryRows(images){return Array.from({length:6},(_,i)=>{const u=images[i]||'';return `<div class="card" style="padding:14px"><div class="ey">Imagen ${i+1}</div><div class="field"><label>URL de imagen</label><input id="cmsGallery${i}" value="${safe(u)}" placeholder="URL de Supabase Storage o imagen pública"></div><div class="actions"><button class="btn out" type="button" onclick="cmsUploadGallery(${i})">Subir imagen</button><button class="btn danger" type="button" onclick="document.querySelector('#cmsGallery${i}').value=''">Quitar</button></div><div id="cmsGalleryPreview${i}" style="margin-top:8px"></div></div>`}).join('')}
function renderGalleryPreviews(images){images.forEach((u,i)=>{const el=document.querySelector('#cmsGalleryPreview'+i);if(el&&u)el.innerHTML=`<img src="${safe(u)}" alt="Galería ${i+1}" style="width:100%;height:120px;object-fit:cover;border:1px solid #222;border-radius:8px">`})}
window.adminSite=async function(c){
 if(!isAdmin()){c.innerHTML='<div class="empty">Acceso no autorizado.</div>';return}
 const {data,error}=await api4.from('site_content').select('key,value,is_public').order('key');
 if(error){c.innerHTML=`<div class="empty">No se pudo cargar el contenido de la landing: ${safe(error.message)}</div>`;return}
 const s=Object.assign({},defaults,Object.fromEntries((data||[]).map(r=>[r.key,r.value||{}])));
 const b=Object.assign({},defaults.brand,s.brand||{}),h=Object.assign({},defaults.hero,s.hero||{}),co=Object.assign({},defaults.contact,s.contact||{}),cm=Object.assign({},defaults.community,s.community||{}),g=Object.assign({},defaults.landing_gallery,s.landing_gallery||{});
 c.innerHTML=`
 <div class="hero"><div class="ey">Content management</div><h2>Controla tu <span>landing.</span></h2><p class="muted">Este es el centro de control del sitio público. Todo lo que guardes aquí vive en Supabase y la landing lo lee sin tocar código.</p></div>
 <div class="card"><div class="ey">Publicación en vivo</div><h2>Una sola fuente de verdad.</h2><p class="muted">WOD, horarios, coaches, planes, leaderboard e Instagram se administran desde sus módulos. Marca, hero, contacto, comunidad y galería se administran aquí.</p><div class="actions"><button class="btn red" type="button" onclick="window.go('classes')">Horarios</button><button class="btn out" type="button" onclick="window.go('coaches')">Coaches</button><button class="btn out" type="button" onclick="window.go('wod')">WOD</button><button class="btn out" type="button" onclick="window.go('plans')">Planes</button><button class="btn out" type="button" onclick="window.go('leaderboard')">Leaderboard</button><button class="btn out" type="button" onclick="window.go('instagram')">Instagram</button></div></div><br>
 <div class="grid grid2">
  <div class="card"><div class="ey">Marca</div><h2>Identidad</h2><div class="form"><div class="field"><label>Logo</label><input id="cmsLogo" value="${safe(b.logo_url||b.logoUrl||'')}" placeholder="URL o sube el logo"></div><div class="field"><label>Instagram</label><input id="cmsInstagram" value="${safe(cm.instagram||b.instagram||'@zona33functionalclub')}"></div><div class="actions"><button class="btn red" type="button" onclick="cmsSaveBrand()">Guardar</button><button class="btn out" type="button" onclick="cmsUpload('logo')">Subir logo</button></div><div id="cmsLogoPreview" style="margin-top:10px"></div></div></div>
  <div class="card"><div class="ey">Hero</div><h2>Portada</h2><div class="form"><div class="field"><label>Título principal</label><textarea id="cmsHeroTitle">${safe(h.title||h.headline)}</textarea></div><div class="field"><label>Texto</label><textarea id="cmsHeroCopy">${safe(h.copy||h.subheadline)}</textarea></div><div class="field"><label>Imagen de portada</label><input id="cmsHeroImage" value="${safe(h.image_url||h.imageUrl||'')}" placeholder="URL o sube la imagen"></div><div class="actions"><button class="btn red" type="button" onclick="cmsSaveHero()">Guardar</button><button class="btn out" type="button" onclick="cmsUpload('hero')">Subir imagen</button></div><div id="cmsHeroPreview" style="margin-top:10px"></div></div></div>
  <div class="card"><div class="ey">Contacto</div><h2>Ubicación</h2><div class="form"><div class="field"><label>Teléfono</label><input id="cmsPhone" value="${safe(co.phone||'')}"></div><div class="field"><label>Dirección</label><textarea id="cmsAddress">${safe(co.address||'')}</textarea></div><button class="btn red" type="button" onclick="cmsSaveContact()">Guardar</button></div></div>
  <div class="card"><div class="ey">Comunidad</div><h2>Presencia social</h2><div class="form"><div class="field"><label>Cuenta de Instagram</label><input id="cmsCommunityIG" value="${safe(cm.instagram||'@zona33functionalclub')}"></div><div class="field"><label>Título de comunidad</label><input id="cmsCommunityHeadline" value="${safe(cm.headline||'MORE THAN A GYM')}"></div><button class="btn red" type="button" onclick="cmsSaveCommunity()">Guardar</button></div></div>
 </div><br>
 <div class="card"><div class="ey">Galería</div><h2>Fotos del landing</h2><p class="muted">Estas imágenes sustituyen las fotos estáticas de la galería del sitio. Puedes subir fotos reales de ZONA 33; no necesitas tocar GitHub.</p><div class="grid grid2">${galleryRows(Array.isArray(g.images)?g.images:[])}</div><br><button class="btn red" type="button" onclick="cmsSaveGallery()">Guardar galería</button></div>`;
 if(b.logo_url||b.logoUrl)document.querySelector('#cmsLogoPreview').innerHTML=`<img src="${safe(b.logo_url||b.logoUrl)}" alt="Logo" style="max-width:180px;max-height:90px;object-fit:contain;background:#080808;border:1px solid #222;border-radius:8px;padding:8px">`;
 if(h.image_url||h.imageUrl)document.querySelector('#cmsHeroPreview').innerHTML=`<img src="${safe(h.image_url||h.imageUrl)}" alt="Hero" style="width:100%;max-height:180px;object-fit:cover;border:1px solid #222;border-radius:8px">`;
 renderGalleryPreviews(Array.isArray(g.images)?g.images:[]);
};
window.cmsSaveBrand=async()=>{try{await save4('brand',{logo_url:q('cmsLogo')||null,logoUrl:q('cmsLogo')||null,instagram:q('cmsInstagram')||null});await save4('community',{instagram:q('cmsInstagram')||null});toast('Marca actualizada.');window.go('site')}catch(e){toast('No se pudo guardar: '+e.message)}};
window.cmsSaveHero=async()=>{try{const v={title:q('cmsHeroTitle'),headline:q('cmsHeroTitle'),copy:q('cmsHeroCopy'),subheadline:q('cmsHeroCopy'),image_url:q('cmsHeroImage')||null,imageUrl:q('cmsHeroImage')||null};await save4('hero',v);toast('Hero actualizado.');window.go('site')}catch(e){toast('No se pudo guardar: '+e.message)}};
window.cmsSaveContact=async()=>{try{await save4('contact',{phone:q('cmsPhone'),address:q('cmsAddress')});toast('Contacto actualizado.');window.go('site')}catch(e){toast('No se pudo guardar: '+e.message)}};
window.cmsSaveCommunity=async()=>{try{await save4('community',{headline:q('cmsCommunityHeadline')||'MORE THAN A GYM',instagram:q('cmsCommunityIG')||'@zona33functionalclub'});toast('Comunidad actualizada.');window.go('site')}catch(e){toast('No se pudo guardar: '+e.message)}};
window.cmsSaveGallery=async()=>{try{const images=Array.from({length:6},(_,i)=>q('cmsGallery'+i)).filter(Boolean);await save4('landing_gallery',{images});toast('Galería publicada en la landing.');window.go('site')}catch(e){toast('No se pudo guardar la galería: '+e.message)}};
window.cmsUpload=async(type)=>{const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=async()=>{const f=i.files?.[0];if(!f)return;if(f.size>8*1024*1024)return toast('Máximo 8 MB.');try{toast('Subiendo…');const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${type}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await api4.storage.from('site-media').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type||'image/jpeg'});if(error)throw error;const {data}=api4.storage.from('site-media').getPublicUrl(path);if(type==='logo')document.querySelector('#cmsLogo').value=data.publicUrl;else document.querySelector('#cmsHeroImage').value=data.publicUrl;toast('Imagen subida. Pulsa Guardar para publicarla.')}catch(e){toast('No se pudo subir: '+e.message)}};i.click()};
window.cmsUploadGallery=async(index)=>{const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=async()=>{const f=i.files?.[0];if(!f)return;if(f.size>8*1024*1024)return toast('Máximo 8 MB.');try{toast('Subiendo imagen…');const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`gallery/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await api4.storage.from('site-media').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type||'image/jpeg'});if(error)throw error;const {data}=api4.storage.from('site-media').getPublicUrl(path);document.querySelector('#cmsGallery'+index).value=data.publicUrl;document.querySelector('#cmsGalleryPreview'+index).innerHTML=`<img src="${safe(data.publicUrl)}" alt="Galería ${index+1}" style="width:100%;height:120px;object-fit:cover;border:1px solid #222;border-radius:8px">`;toast('Imagen subida. Pulsa Guardar galería.')}catch(e){toast('No se pudo subir: '+e.message)}};i.click()};
})();