(()=>{'use strict';
const api=window.sb;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const toast=m=>window.toast?window.toast(m):alert(m);
async function uploadCoachPhoto(){const input=document.createElement('input');input.type='file';input.accept='image/*';return new Promise((resolve,reject)=>{input.onchange=async()=>{const f=input.files?.[0];if(!f)return resolve('');try{if(f.size>8*1024*1024)throw new Error('La foto debe pesar menos de 8 MB.');const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`coaches/${Date.now()}-${crypto.randomUUID()}.${ext}`;const q=await api.storage.from('site-media').upload(path,f,{upsert:false,contentType:f.type||'image/jpeg',cacheControl:'3600'});if(q.error)throw q.error;resolve(api.storage.from('site-media').getPublicUrl(path).data.publicUrl)}catch(e){reject(e)}};input.click()})}
async function loadCoaches(){const r=await api.from('coaches').select('*').order('name');if(r.error)throw r.error;return r.data||[]}
function coachCard(x){return `<div class='card z13-coach' data-id='${esc(x?.id||'')}' style='padding:14px'><div class='row'><div class='field'><label>Nombre</label><input class='z13-name' value='${esc(x?.name||'')}'></div><div class='field'><label>Especialidad</label><input class='z13-spec' value='${esc(x?.specialty||'')}'></div></div><div class='field'><label>Bio</label><textarea class='z13-bio' placeholder='Descripción breve del coach'>${esc(x?.bio||'')}</textarea></div><div class='field'><label>Foto del coach</label><div class='row'><input class='z13-photo' value='${esc(x?.photo_url||'')}' placeholder='Puedes pegar una URL o subir un archivo'><button class='btn out z13-upload'>Subir foto</button></div></div><div class='z13-preview'>${x?.photo_url?`<img src='${esc(x.photo_url)}' alt='${esc(x.name||'Coach')}' style='width:120px;height:120px;object-fit:cover;border-radius:12px;margin-top:6px'>`:''}</div><div class='row' style='margin-top:10px'><div class='field'><label>Activo</label><select class='z13-active'><option value='true' ${x?.is_active!==false?'selected':''}>Sí</option><option value='false' ${x?.is_active===false?'selected':''}>No</option></select></div><div></div></div><div class='actions' style='margin-top:10px'><button class='btn red z13-save'>Guardar coach</button></div></div>`}
async function install(){for(let i=0;i<80;i++){if(typeof window.adminCoaches==='function'&&api){if(window.__Z13_COACHES)return;window.__Z13_COACHES=true;window.adminCoaches=async c=>{const r=await loadCoaches().catch(e=>{c.innerHTML=`<div class='empty'>No se pudieron cargar coaches: ${esc(e.message)}</div>`;return null});if(!r)return;const shell=document.createElement('div');shell.innerHTML=`<div class='hero'><div class='ey'>Equipo</div><h2>Coaches.</h2><p class='muted'>Edita nombre, especialidad, bio, foto y disponibilidad. Puedes subir la foto directamente desde tu computadora.</p><button class='btn red' id='z13add'>+ Agregar coach</button></div><div class='grid grid2' id='z13list'></div>`;c.innerHTML='';c.appendChild(shell);const list=shell.querySelector('#z13list');let rows=[...r];const bind=()=>{list.querySelectorAll('.z13-upload').forEach(b=>b.onclick=async()=>{try{const u=await uploadCoachPhoto();if(!u)return;const root=b.closest('.z13-coach');root.querySelector('.z13-photo').value=u;const p=root.querySelector('.z13-preview');p.innerHTML=`<img src='${esc(u)}' alt='Coach' style='width:120px;height:120px;object-fit:cover;border-radius:12px;margin-top:6px'>`;}catch(e){toast('No se pudo subir la foto: '+e.message)}});list.querySelectorAll('.z13-save').forEach(b=>b.onclick=async()=>{const root=b.closest('.z13-coach'),id=root.dataset.id,v=s=>root.querySelector(s)?.value?.trim()||'';const p={name:v('.z13-name'),specialty:v('.z13-spec')||null,bio:v('.z13-bio')||null,photo_url:v('.z13-photo')||null,is_active:root.querySelector('.z13-active')?.value==='true',updated_at:new Date().toISOString()};if(!p.name)return toast('Escribe el nombre del coach.');const q=id?await api.from('coaches').update(p).eq('id',id):await api.from('coaches').insert(p);if(q.error)return toast('No se pudo guardar: '+q.error.message);toast('Coach guardado.');window.go('coaches')})};const draw=()=>{list.innerHTML=rows.map(coachCard).join('')||`<div class='empty'>No hay coaches todavía.</div>`;bind()};shell.querySelector('#z13add').onclick=()=>{rows.unshift({id:'',name:'',specialty:'',bio:'',photo_url:'',is_active:true});draw()};draw()};return}await new Promise(r=>setTimeout(r,250))}}
install();
})();
