(()=>{
const U='https://ponhllwbvhtczaphfdgw.supabase.co',K='sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
const api4=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const q=id=>document.querySelector('#'+id)?.value?.trim()||'';
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function save4(key,value){const {data:{user}}=await api4.auth.getUser();const {error}=await api4.from('site_content').upsert({key,value,is_public:true,updated_by:user?.id||null,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error}
window.adminSite=async function(c){
 const {data,error}=await api4.from('site_content').select('key,value').order('key');
 if(error){c.innerHTML='<div class="empty">No se pudo cargar el contenido de la landing.</div>';return}
 const s=Object.fromEntries((data||[]).map(r=>[r.key,r.value||{}])),b=s.brand||{},h=s.hero||{},co=s.contact||{},cm=s.community||{};
 c.innerHTML=`<div class="hero"><div class="ey">Content management</div><h2>Controla tu <span>landing.</span></h2><p class="muted">Un solo lugar para actualizar el contenido público de ZONA 33. Los cambios se reflejan en la landing sin editar código.</p></div>
 <div class="grid grid2">
 <div class="card"><div class="ey">Marca</div><h2>Identidad</h2><div class="form"><div class="field"><label>Logo</label><input id="cmsLogo" value="${safe(b.logo_url||b.logoUrl||'')}" placeholder="URL o súbelo abajo"></div><div class="field"><label>Instagram</label><input id="cmsInstagram" value="${safe(cm.instagram||b.instagram||'@zona33functionalclub')}"></div><div class="actions"><button class="btn red" onclick="cmsSaveBrand()">Guardar marca</button><button class="btn out" onclick="cmsUpload('logo')">Subir logo</button></div><div id="cmsLogoPreview" style="margin-top:10px"></div></div></div>
 <div class="card"><div class="ey">Hero</div><h2>Portada</h2><div class="form"><div class="field"><label>Título principal</label><textarea id="cmsHeroTitle">${safe(h.title||h.headline||'SER TU MEJOR VERSIÓN')}</textarea></div><div class="field"><label>Subtítulo / copy</label><textarea id="cmsHeroCopy">${safe(h.copy||h.subheadline||'Aquí empieza la fortaleza')}</textarea></div><div class="field"><label>Imagen de portada</label><input id="cmsHeroImage" value="${safe(h.image_url||h.imageUrl||'')}" placeholder="URL o súbela abajo"></div><div class="actions"><button class="btn red" onclick="cmsSaveHero()">Guardar hero</button><button class="btn out" onclick="cmsUpload('hero')">Subir imagen</button></div><div id="cmsHeroPreview" style="margin-top:10px"></div></div></div>
 <div class="card"><div class="ey">Contacto</div><h2>Ubicación</h2><div class="form"><div class="field"><label>Teléfono</label><input id="cmsPhone" value="${safe(co.phone||b.phone||'2229195074')}"></div><div class="field"><label>Dirección</label><textarea id="cmsAddress">${safe(co.address||b.address||'')}</textarea></div><button class="btn red" onclick="cmsSaveContact()">Guardar contacto</button></div></div>
 <div class="card"><div class="ey">Comunidad</div><h2>Presencia social</h2><div class="form"><div class="field"><label>Instagram mostrado</label><input id="cmsCommunityIG" value="${safe(cm.instagram||'@zona33functionalclub')}"></div><div class="field"><label>Texto de comunidad</label><input id="cmsCommunityHeadline" value="${safe(cm.headline||'MORE THAN A GYM')}"></div><button class="btn red" onclick="cmsSaveCommunity()">Guardar comunidad</button></div></div></div><br>
 <div class="card"><div class="ey">Contenido dinámico</div><h2>Resto de la landing</h2><p class="muted">Estas secciones se editan directamente desde sus módulos del portal y alimentan la landing: WOD, horarios, coaches, planes, leaderboard, Instagram y comunidad.</p><div class="actions"><button class="btn red" onclick="go('wod')">WOD</button><button class="btn out" onclick="go('classes')">Horarios</button><button class="btn out" onclick="go('coaches')">Coaches</button><button class="btn out" onclick="go('plans')">Planes</button><button class="btn out" onclick="go('leaderboard')">Leaderboard</button><button class="btn out" onclick="go('instagram')">Instagram</button><button class="btn out" onclick="go('community')">Comunidad</button></div></div>`;
 if(b.logo_url||b.logoUrl)document.querySelector('#cmsLogoPreview').innerHTML=`<img src="${safe(b.logo_url||b.logoUrl)}" style="max-width:180px;max-height:90px;object-fit:contain;background:#080808;border:1px solid #222;border-radius:8px;padding:8px">`;
 if(h.image_url||h.imageUrl)document.querySelector('#cmsHeroPreview').innerHTML=`<img src="${safe(h.image_url||h.imageUrl)}" style="width:100%;max-height:180px;object-fit:cover;border:1px solid #222;border-radius:8px">`;
};
window.cmsSaveBrand=async()=>{try{await save4('brand',{...(window.__z33Brand||{}),logo_url:q('cmsLogo')||null,logoUrl:q('cmsLogo')||null,instagram:q('cmsInstagram')||null});await save4('community',{...(window.__z33Community||{}),instagram:q('cmsInstagram')||null});toast('Marca actualizada.');window.go('site')}catch(e){toast('No se pudo guardar: '+e.message)}};
window.cmsSaveHero=async()=>{try{await save4('hero',{title:q('cmsHeroTitle'),headline:q('cmsHeroTitle'),copy:q('cmsHeroCopy'),subheadline:q('cmsHeroCopy'),image_url:q('cmsHeroImage')||null,imageUrl:q('cmsHeroImage')||null});toast('Hero actualizado.');window.go('site')}catch(e){toast('No se pudo guardar: '+e.message)}};
window.cmsSaveContact=async()=>{try{await save4('contact',{phone:q('cmsPhone'),address:q('cmsAddress')});toast('Contacto actualizado.');window.go('site')}catch(e){toast('No se pudo guardar: '+e.message)}};
window.cmsSaveCommunity=async()=>{try{await save4('community',{headline:q('cmsCommunityHeadline')||'MORE THAN A GYM',instagram:q('cmsCommunityIG')||'@zona33functionalclub'});toast('Comunidad actualizada.');window.go('site')}catch(e){toast('No se pudo guardar: '+e.message)}};
window.cmsUpload=async(type)=>{const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=async()=>{const f=i.files?.[0];if(!f)return;if(f.size>8*1024*1024)return toast('Máximo 8 MB.');try{toast('Subiendo…');const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${type}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await api4.storage.from('site-media').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type||'image/jpeg'});if(error)throw error;const {data}=api4.storage.from('site-media').getPublicUrl(path);if(type==='logo')document.querySelector('#cmsLogo').value=data.publicUrl;else document.querySelector('#cmsHeroImage').value=data.publicUrl;toast('Imagen subida. Pulsa Guardar para publicarla.')}catch(e){toast('No se pudo subir: '+e.message)}};i.click()};
})();
