(()=>{
'use strict';
const U='https://ponhllwbvhtczaphfdgw.supabase.co',K='sb_publishable_okgoHkX2YZFtQ9P72ckztQ_jiCuWN-6';
const api=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const val=id=>document.querySelector('#'+id)?.value?.trim()||'';
async function save(key,value){const {data:{user}}=await api.auth.getUser();const {error}=await api.from('site_content').upsert({key,value,is_public:true,updated_by:user?.id||null,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error;}
async function upload(){const input=document.createElement('input');input.type='file';input.accept='image/*';input.multiple=true;input.onchange=async()=>{const files=[...(input.files||[])].slice(0,5);if(!files.length)return;try{const urls=[];for(const f of files){if(f.size>8*1024*1024)throw new Error('Cada imagen debe pesar menos de 8 MB.');const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`landing/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await api.storage.from('site-media').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type||'image/jpeg'});if(error)throw error;urls.push(api.storage.from('site-media').getPublicUrl(path).data.publicUrl);}urls.forEach((u,i)=>{const el=document.querySelector('#cmsGallery'+(i+1));if(el)el.value=u;});window.toast('Imágenes subidas. Pulsa guardar galería.');}catch(e){window.toast('No se pudieron subir las imágenes: '+e.message)}};input.click();}
async function boot(){for(let i=0;i<40;i++){if(typeof window.adminSite==='function'){
 const original=window.adminSite;
 window.adminSite=async function(c){await original(c);const {data}=await api.from('site_content').select('key,value').eq('key','landing_gallery').maybeSingle();const imgs=Array.isArray(data?.value?.images)?data.value.images:[];const card=document.createElement('div');card.className='card';card.innerHTML=`<div class="ey">Galería</div><h2>Fotos del landing</h2><p class="muted">Cambia las fotos que aparecen en las secciones visuales del landing. Puedes pegar URLs o subir hasta 5 imágenes.</p><div class="form">${[1,2,3,4,5].map((n)=>`<div class="field"><label>Imagen ${n}</label><input id="cmsGallery${n}" value="${esc(imgs[n-1]||'')}" placeholder="https://..."></div>`).join('')}<div class="actions"><button class="btn red" id="cmsSaveGalleryBtn">Guardar galería</button><button class="btn out" id="cmsUploadGalleryBtn">Subir imágenes</button></div><div class="grid" id="cmsGalleryPreview" style="grid-template-columns:repeat(5,minmax(0,1fr));margin-top:12px"></div></div>`;c.appendChild(card);const preview=()=>{const p=document.querySelector('#cmsGalleryPreview');if(!p)return;p.innerHTML=[1,2,3,4,5].map(n=>{const u=val('cmsGallery'+n);return u?`<img src="${esc(u)}" style="width:100%;aspect-ratio:1;object-fit:cover;border-radius:8px;border:1px solid #2a2a2a">`:''}).join('')};[1,2,3,4,5].forEach(n=>document.querySelector('#cmsGallery'+n)?.addEventListener('input',preview));document.querySelector('#cmsSaveGalleryBtn').onclick=async()=>{try{await save('landing_gallery',{images:[1,2,3,4,5].map(n=>val('cmsGallery'+n)).filter(Boolean)});window.toast('Galería actualizada.');window.go('site')}catch(e){window.toast('No se pudo guardar: '+e.message)}};document.querySelector('#cmsUploadGalleryBtn').onclick=upload;preview();};
 if(typeof window.clientPayments==='function'){
  const originalPayments=window.clientPayments;
  window.clientPayments=function(c){originalPayments(c);const hero=c.querySelector('.hero');if(hero&&!c.querySelector('#z33MercadoPago')){const box=document.createElement('div');box.className='card';box.id='z33MercadoPago';box.innerHTML='<div class="ey">Pago de membresía</div><h2>Renueva tu membresía.</h2><p class="muted">Realiza tu pago de forma segura mediante Mercado Pago. Después de pagar, tu comprobante quedará sujeto a validación por ZONA 33.</p><a class="btn red" href="https://link.mercadopago.com.mx/zona33" target="_blank" rel="noopener noreferrer" style="display:inline-flex;align-items:center;justify-content:center;text-decoration:none">PAGAR CON MERCADO PAGO</a>';c.insertBefore(box,c.children[1]||null);}}
 }
 return;
}await new Promise(r=>setTimeout(r,250));}}
boot();
})();
