(()=>{
  if(typeof sb==='undefined') return;
  const escF=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const moneyF=v=>'$'+Number(v||0).toLocaleString('es-MX',{minimumFractionDigits:0,maximumFractionDigits:0});
  const dateF=v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-MX',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
  const isoDate=()=>new Date().toISOString().slice(0,10);
  window.__finance={tab:'payments',payments:[],memberships:[],plans:[],founders:[],expenses:[],clients:[],coaches:[]};

  const oldNav=nav;
  nav=()=>{
    if(role==='admin') return [['overview','Dashboard'],['clients','Clientes'],['classes','Clases / horarios'],['coaches','Coaches'],['finance','Finanzas'],['site','Editar landing']];
    return oldNav();
  };
  labels.finance='Finanzas';
  const oldRenderShell=renderShell;
  renderShell=()=>{
    if(role!=='admin') return oldRenderShell();
    app.innerHTML=`<div class="shell"><aside class="side"><a class="brand" href="/"><img src="https://raw.githubusercontent.com/perezdayana82/ZONA33/main/assets/zona33-logo.svg" alt="ZONA 33"><strong>ZONA 33</strong></a><div class="role">Administrador · portal</div><nav class="nav" id="nav">${nav().map(([k,v])=>`<button data-page="${k}">${v}</button>`).join('')}</nav><div class="sidefoot">ZONA 33 FUNCTIONAL CLUB<br>Panel administrativo</div></aside><main class="main"><header class="top"><div><div class="ey">ZONA 33</div><h1 id="pageTitle">Dashboard</h1></div><div class="top-actions"><span class="pill ok">Conectado</span><button class="btn out" onclick="location.href='/'">Sitio</button><button class="btn danger" onclick="logout()">Salir</button></div></header><section class="content" id="content"></section><div class="mobilebar"><button class="btn red" onclick="go('overview')">Inicio</button><button class="btn" onclick="location.href='/'">Sitio</button><button class="btn danger" onclick="logout()">Salir</button></div></main></div>`;
    document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
  };
  const oldGo=go;
  go=(page)=>{ if(page==='finance'){document.querySelector('#pageTitle').textContent='Finanzas';document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));financeLoad('payments');return;} oldGo(page); };

  function injectStyle(){
    if(document.getElementById('financeStyle')) return;
    const s=document.createElement('style'); s.id='financeStyle'; s.textContent=`
      .fin-tabs{display:flex;flex-wrap:wrap;gap:4px;border-bottom:1px solid #e4e7eb;margin:0 0 16px}
      .fin-tabs button{border:0;background:transparent;padding:11px 13px;color:#69727d;font-size:11px;font-weight:700;border-bottom:2px solid transparent}
      .fin-tabs button.active{color:#b51324;border-bottom-color:#c91428}
      .fin-toolbar{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:12px}
      .fin-actions{display:flex;gap:7px;flex-wrap:wrap}
      .fin-filter{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}
      .fin-filter button{min-height:34px;padding:7px 10px;border-radius:999px;border:1px solid #dfe3e7;background:#fff;color:#68707a;font-size:10px;font-weight:700}
      .fin-filter button.active{background:#17191d;color:#fff;border-color:#17191d}
      .fin-grid5{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}
      .fin-kpi{background:#fff;border:1px solid #e5e7ea;border-radius:12px;padding:15px;min-width:0}
      .fin-kpi small{display:block;color:#7b838c;font-size:9px;text-transform:uppercase;letter-spacing:.06em;font-weight:800}
      .fin-kpi strong{display:block;font-size:23px;margin-top:6px}
      .fin-chart{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}
      .fin-bar-row{display:grid;grid-template-columns:95px 1fr 74px;gap:8px;align-items:center;margin:9px 0;font-size:10px}
      .fin-bar{height:10px;background:#eef0f3;border-radius:999px;overflow:hidden}.fin-bar i{display:block;height:100%;background:#c91428;border-radius:999px}
      .fin-meta{color:#7a828c;font-size:10px}.fin-code{font-weight:800;letter-spacing:.05em}
      .fin-lock{font-size:9px;color:#b42318;background:#fff0ef;border:1px solid #f1d0cc;border-radius:999px;padding:3px 7px;font-weight:800}
      @media(max-width:1100px){.fin-grid5{grid-template-columns:repeat(2,minmax(0,1fr))}.fin-chart{grid-template-columns:1fr}}
      @media(max-width:650px){.fin-grid5{grid-template-columns:1fr}}
    `; document.head.appendChild(s);
  }

  async function fetchFinance(){
    const f=window.__finance;
    const [payments,memberships,plans,founders,expenses,clients]=await Promise.all([
      sb.from('payments').select('*,profiles(full_name,email),membership_plans(name,is_founder_plan)').order('payment_date',{ascending:false}).order('created_at',{ascending:false}),
      sb.from('memberships').select('*,profiles(full_name,email),membership_plans(name,price,is_founder_plan)').order('created_at',{ascending:false}),
      sb.from('membership_plans').select('*').order('sort_order').order('name'),
      sb.from('founder_codes').select('*').order('created_at',{ascending:false}),
      sb.from('expenses').select('*').order('expense_date',{ascending:false}).order('created_at',{ascending:false}),
      sb.from('profiles').select('id,full_name,email,phone').eq('role','cliente').order('full_name')
    ]);
    f.payments=payments.data||[]; f.memberships=memberships.data||[]; f.plans=plans.data||[]; f.founders=founders.data||[]; f.expenses=expenses.data||[]; f.clients=clients.data||[];
  }

  function financeLoad(tab='payments'){
    injectStyle(); window.__finance.tab=tab; financeFetchAndRender(tab);
  }
  async function financeFetchAndRender(tab){
    const c=document.querySelector('#content'); c.innerHTML='<div class="card"><div class="muted">Cargando finanzas…</div></div>';
    await fetchFinance();
    window.__finance.tab=tab;
    renderFinance(c,tab);
  }
  function tabbar(tab){
    const tabs=[['payments','Pagos'],['memberships','Membresías'],['plans','Planes'],['founders','Códigos de fundadores'],['reports','Reportes']];
    return `<div class="fin-tabs">${tabs.map(([k,v])=>`<button class="${tab===k?'active':''}" onclick="financeLoad('${k}')">${v}</button>`).join('')}</div>`;
  }
  function financeHeader(tab){return `<div class="hero"><div class="ey">Administración</div><h2>Finanzas.</h2><p class="muted">Pagos, membresías, planes, códigos fundadores y reportes en un solo lugar.</p>${tabbar(tab)}</div>`}

  function renderFinance(c,tab){
    if(tab==='payments') return renderPayments(c);
    if(tab==='memberships') return renderMemberships(c);
    if(tab==='plans') return renderPlans(c);
    if(tab==='founders') return renderFounders(c);
    return renderReports(c);
  }

  function renderPayments(c){
    const rows=window.__finance.payments;
    c.innerHTML=`${financeHeader('payments')}<div class="card"><div class="fin-toolbar"><div><input id="finPaySearch" placeholder="Buscar cliente o concepto" style="width:min(360px,100%);padding:11px;border:1px solid #dfe3e7;border-radius:9px"></div><div class="fin-actions"><button class="btn out" onclick="paymentForm()">Registrar pago</button><button class="btn red" onclick="expenseForm()">Nuevo egreso</button></div></div><div class="fin-filter" id="payFilters"><button class="active" data-s="">Todos</button><button data-s="approved">Pagados</button><button data-s="pending">Pendientes</button><button data-s="rejected">Rechazados</button></div><div class="table-wrap"><table class="tbl"><thead><tr><th>Cliente</th><th>Concepto</th><th>Monto</th><th>Fecha</th><th>Método</th><th>Estado</th><th></th></tr></thead><tbody id="finPayBody"></tbody></table></div></div>`;
    const draw=(data)=>document.querySelector('#finPayBody').innerHTML=data.length?data.map(x=>`<tr><td><b>${escF(x.profiles?.full_name||'Cliente')}</b><small class="fin-meta">${escF(x.profiles?.email||'')}</small></td><td>${escF(x.concept||x.membership_plans?.name||'Membresía')}</td><td><b>${moneyF(x.amount)}</b></td><td>${dateF(x.payment_date||x.created_at?.slice(0,10))}</td><td>${escF(x.method||'—')}</td><td><span class="pill ${x.status==='approved'?'ok':x.status==='pending'?'warn':'bad'}">${x.status==='approved'?'Pagado':x.status==='pending'?'Pendiente':'Rechazado'}</span></td><td><button class="btn out" onclick="paymentForm('${x.id}')">Editar</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty">No hay pagos.</div></td></tr>';
    draw(rows);
    document.querySelectorAll('#payFilters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#payFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const q=(document.querySelector('#finPaySearch').value||'').toLowerCase();draw(rows.filter(x=>(!b.dataset.s||x.status===b.dataset.s)&&(!q||(`${x.profiles?.full_name||''} ${x.profiles?.email||''} ${x.concept||''} ${x.membership_plans?.name||''}`).toLowerCase().includes(q))))});
    document.querySelector('#finPaySearch').oninput=()=>{const q=document.querySelector('#finPaySearch').value.toLowerCase();const active=document.querySelector('#payFilters .active')?.dataset.s||'';draw(rows.filter(x=>(!active||x.status===active)&&(`${x.profiles?.full_name||''} ${x.profiles?.email||''} ${x.concept||''} ${x.membership_plans?.name||''}`).toLowerCase().includes(q)))};
  }

  async function paymentForm(id){
    const p=id?window.__finance.payments.find(x=>x.id===id):null;
    const clients=window.__finance.clients;
    modal(p?'Editar pago':'Registrar pago',`<form class="form" onsubmit="saveFinancePayment(event,'${id||''}')"><div class="row"><div class="field"><label>Cliente</label><select id="fpclient" required><option value="">Seleccionar</option>${clients.map(x=>`<option value="${x.id}" ${p?.profile_id===x.id?'selected':''}>${escF(x.full_name)} — ${escF(x.email||'')}</option>`).join('')}</select></div><div class="field"><label>Concepto</label><input id="fpconcept" value="${escF(p?.concept||p?.membership_plans?.name||'Mensualidad')}" required></div></div><div class="row"><div class="field"><label>Monto</label><input id="fpamount" type="number" min="0" step="0.01" value="${escF(p?.amount||'500')}" required></div><div class="field"><label>Fecha</label><input id="fpdate" type="date" value="${escF(p?.payment_date||isoDate())}" required></div></div><div class="row"><div class="field"><label>Método</label><select id="fpmethod"><option value="transferencia">Transferencia</option><option value="ficha">Ficha</option><option value="online">Online</option><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta</option></select></div><div class="field"><label>Estado</label><select id="fpstatus"><option value="approved">Pagado</option><option value="pending">Pendiente</option><option value="rejected">Rechazado</option></select></div></div><div class="field"><label>Notas</label><textarea id="fpnotes">${escF(p?.notes||'')}</textarea></div><div class="muted">Los pagos de fundador quedan bloqueados a <b>$500</b> cuando corresponda.</div><div class="actions"><button type="button" class="btn out" onclick="closeModal()">Cancelar</button><button class="btn red">Guardar</button>${p?`<button type="button" class="btn danger" onclick="deleteFinancePayment('${p.id}')">Eliminar</button>`:''}</div></form>`);
    const m=document.querySelector('#fpmethod'); if(p?.method) m.value=p.method; const st=document.querySelector('#fpstatus'); if(p?.status) st.value=p.status;
    const applyLock=async()=>{const idc=document.querySelector('#fpclient')?.value;if(!idc)return;const isFounder=window.__finance.memberships.some(m=>m.profile_id===idc&&m.founder_code_id&&m.membership_plans?.is_founder_plan);const input=document.querySelector('#fpamount'); if(input){input.value=isFounder?'500':input.value||'500'; input.readOnly=isFounder; input.title=isFounder?'Precio fundador fijo de $500':'';}};
    document.querySelector('#fpclient').addEventListener('change',applyLock); await applyLock();
  }
  window.paymentForm=paymentForm;
  window.saveFinancePayment=async(e,id)=>{e.preventDefault();const client=fpclient.value;const isFounder=window.__finance.memberships.some(m=>m.profile_id===client&&m.founder_code_id&&m.membership_plans?.is_founder_plan);const payload={profile_id:client,concept:fpconcept.value,amount:isFounder?500:Number(fpamount.value),payment_date:fpdate.value,method:fpmethod.value,status:fpstatus.value,notes:fpnotes.value||null};let r=id?await sb.from('payments').update(payload).eq('id',id):await sb.from('payments').insert(payload);if(r.error)return toast(r.error.message);closeModal();await financeFetchAndRender('payments');toast('Pago guardado.')};
  window.deleteFinancePayment=async(id)=>{if(!confirm('¿Eliminar este pago?'))return;const r=await sb.from('payments').delete().eq('id',id);if(r.error)return toast(r.error.message);closeModal();await financeFetchAndRender('payments');toast('Pago eliminado.')};

  window.expenseForm=()=>modal('Nuevo egreso','<form class="form" onsubmit="saveExpense(event)"><div class="row"><div class="field"><label>Concepto</label><input id="exconcept" required></div><div class="field"><label>Monto</label><input id="examount" type="number" step="0.01" min="0" required></div></div><div class="row"><div class="field"><label>Fecha</label><input id="exdate" type="date" value="'+isoDate()+'" required></div><div class="field"><label>Categoría</label><input id="excat" placeholder="Renta, insumos, servicios…"></div></div><div class="row"><div class="field"><label>Método</label><select id="exmethod"><option value="transferencia">Transferencia</option><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta</option><option value="online">Online</option></select></div><div class="field"><label>Notas</label><input id="exnotes"></div></div><div class="actions"><button type="button" class="btn out" onclick="closeModal()">Cancelar</button><button class="btn red">Guardar egreso</button></div></form>');
  window.saveExpense=async e=>{e.preventDefault();const r=await sb.from('expenses').insert({concept:exconcept.value,amount:Number(examount.value),expense_date:exdate.value,category:excat.value||null,method:exmethod.value,notes:exnotes.value||null,created_by:me.id});if(r.error)return toast(r.error.message);closeModal();await financeFetchAndRender('reports');toast('Egreso guardado.')};

  function renderMemberships(c){const rows=window.__finance.memberships;c.innerHTML=`${financeHeader('memberships')}<div class="card"><div class="fin-toolbar"><input id="finMemSearch" placeholder="Buscar cliente" style="width:min(360px,100%);padding:11px;border:1px solid #dfe3e7;border-radius:9px"><div class="fin-filter"><button class="active" data-m="">Todos</button><button data-m="active">Activas</button><button data-m="pending">Pendientes</button><button data-m="expired">Vencidas</button></div></div><div class="table-wrap"><table class="tbl"><thead><tr><th>Cliente</th><th>Plan</th><th>Inicio</th><th>Vencimiento</th><th>Estado</th><th></th></tr></thead><tbody id="finMemBody"></tbody></table></div></div>`;const draw=data=>document.querySelector('#finMemBody').innerHTML=data.length?data.map(x=>`<tr><td><b>${escF(x.profiles?.full_name||'')}</b><small class="fin-meta">${escF(x.profiles?.email||'')}</small></td><td>${escF(x.membership_plans?.name||'—')} ${x.membership_plans?.is_founder_plan?'<span class="fin-lock">$500 FIJO</span>':''}</td><td>${dateF(x.start_date)}</td><td>${dateF(x.end_date)}</td><td><span class="pill ${x.status==='active'?'ok':x.status==='pending'?'warn':'bad'}">${escF(x.status)}</span></td><td><button class="btn out" onclick="membershipView('${x.id}')">Ver</button></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No hay membresías.</div></td></tr>';draw(rows);document.querySelectorAll('.fin-filter button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.fin-filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const q=(finMemSearch.value||'').toLowerCase();draw(rows.filter(x=>(!b.dataset.m||x.status===b.dataset.m)&&(`${x.profiles?.full_name||''} ${x.membership_plans?.name||''}`).toLowerCase().includes(q)))});finMemSearch.oninput=()=>{const q=finMemSearch.value.toLowerCase();const active=document.querySelector('.fin-filter .active')?.dataset.m||'';draw(rows.filter(x=>(!active||x.status===active)&&(`${x.profiles?.full_name||''} ${x.membership_plans?.name||''}`).toLowerCase().includes(q)))};}
  window.membershipView=id=>{const m=window.__finance.memberships.find(x=>x.id===id);if(!m)return;modal('Detalle de membresía',`<div class="list"><div class="item"><div><b>${escF(m.profiles?.full_name||'')}</b><small>${escF(m.profiles?.email||'')}</small></div><span class="pill ${m.status==='active'?'ok':'warn'}">${escF(m.status)}</span></div><div class="item"><div><b>${escF(m.membership_plans?.name||'Plan')}</b><small>${dateF(m.start_date)} → ${dateF(m.end_date)}</small></div><strong>${m.membership_plans?.is_founder_plan?'$500':'$'+Number(m.membership_plans?.price||0).toLocaleString('es-MX')}</strong></div></div><br><button class="btn out" onclick="closeModal()">Cerrar</button>`)};

  function renderPlans(c){const rows=window.__finance.plans;c.innerHTML=`${financeHeader('plans')}<div class="fin-grid5">${rows.map(p=>`<div class="card"><div class="ey">${p.is_founder_plan?'Fundadores':'Plan'}</div><h3>${escF(p.name)}</h3><div style="font-size:27px;font-weight:800">${moneyF(p.price)}</div><p class="muted">${escF(p.description||'')}<br>${p.duration_days||30} días</p><span class="pill ${p.is_active?'ok':'bad'}">${p.is_active?'Activo':'Inactivo'}</span>${p.is_founder_plan?'<div style="margin-top:9px"><span class="fin-lock">PRECIO FIJO $500</span></div>':''}<br><br><button class="btn out" onclick="financePlanForm('${p.id}')">Editar</button></div>`).join('')}</div>`;}
  window.financePlanForm=id=>{const p=window.__finance.plans.find(x=>x.id===id);modal(p?'Editar plan':'Nuevo plan',`<form class="form" onsubmit="saveFinancePlan(event,'${id||''}')"><div class="field"><label>Nombre</label><input id="fplname" value="${escF(p?.name||'')}" required></div><div class="field"><label>Descripción</label><textarea id="fpldesc">${escF(p?.description||'')}</textarea></div><div class="row"><div class="field"><label>Precio</label><input id="fplprice" type="number" step="0.01" value="${escF(p?.price||'')}" ${p?.is_founder_plan?'readonly':''}></div><div class="field"><label>Duración (días)</label><input id="fpldays" type="number" value="${escF(p?.duration_days||30)}"></div></div><div class="field"><label>Etiqueta</label><input id="fpllabel" value="${escF(p?.promo_label||'')}"></div><div class="muted">${p?.is_founder_plan?'El precio fundador está bloqueado en $500 y no se puede modificar.':'Plan normal.'}</div><button class="btn red">Guardar plan</button></form>')};
  window.saveFinancePlan=async(e,id)=>{e.preventDefault();const existing=id?window.__finance.plans.find(x=>x.id===id):null;const payload={name:fplname.value,description:fpldesc.value,price:existing?.is_founder_plan?500:Number(fplprice.value),duration_days:Number(fpldays.value)||30,promo_label:fpllabel.value||null,updated_at:new Date().toISOString()};let r=id?await sb.from('membership_plans').update(payload).eq('id',id):await sb.from('membership_plans').insert({...payload,is_active:true,is_founder_plan:false});if(r.error)return toast(r.error.message);closeModal();await financeFetchAndRender('plans');toast('Plan guardado.')};

  function renderFounders(c){const rows=window.__finance.founders;c.innerHTML=`${financeHeader('founders')}<div class="card"><div class="fin-toolbar"><div class="muted">Los códigos nuevos dan acceso al precio fundador fijo de $500 al mes.</div><button class="btn red" onclick="founderFinanceForm()">Crear código</button></div><div class="table-wrap"><table class="tbl"><thead><tr><th>Código</th><th>Estado</th><th>Cliente</th><th>Creado</th><th>Usado</th><th></th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td class="fin-code">${escF(x.code)}</td><td><span class="pill ${x.is_active===false?'bad':x.used_by?'warn':'ok'}">${x.is_active===false?'Inactivo':x.used_by?'Usado':'Activo'}</span></td><td>${escF(x.used_by?'Asignado':'Disponible')}</td><td>${dateF(x.created_at?.slice(0,10))}</td><td>${x.used_at?dateF(x.used_at.slice(0,10)):'—'}</td><td><div class="actions"><button class="btn out" onclick="founderFinanceForm('${x.id}')">Editar</button>${!x.used_by?`<button class="btn ${x.is_active===false?'red':'danger'}" onclick="toggleFounder('${x.id}',${x.is_active!==false})">${x.is_active===false?'Activar':'Desactivar'}</button>`:''}</div></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No hay códigos.</div></td></tr>'}</tbody></table></div></div>`;}
  window.founderFinanceForm=id=>{const x=id?window.__finance.founders.find(v=>v.id===id):null;modal(x?'Editar código fundador':'Crear código fundador',`<form class="form" onsubmit="saveFounderFinance(event,'${id||''}')"><div class="field"><label>Código</label><input id="ffcode" value="${escF(x?.code||'')}" required placeholder="Z33-FOUND-001"></div><div class="muted">El código se activa o desactiva desde la lista. Una vez usado no puede reasignarse.</div><div class="actions"><button type="button" class="btn out" onclick="closeModal()">Cancelar</button><button class="btn red">Guardar</button>${x&&!x.used_by?`<button type="button" class="btn danger" onclick="deleteFounderFinance('${x.id}')">Eliminar</button>`:''}</div></form>`) };
  window.saveFounderFinance=async(e,id)=>{e.preventDefault();const code=ffcode.value.trim().toUpperCase();const payload={code};const r=id?await sb.from('founder_codes').update(payload).eq('id',id):await sb.from('founder_codes').insert({...payload,is_active:true});if(r.error)return toast(r.error.message);closeModal();await financeFetchAndRender('founders');toast('Código guardado.')};
  window.toggleFounder=async(id,current)=>{const r=await sb.from('founder_codes').update({is_active:!current}).eq('id',id);if(r.error)return toast(r.error.message);await financeFetchAndRender('founders');toast(!current?'Código activado.':'Código desactivado.')};
  window.deleteFounderFinance=async id=>{if(!confirm('¿Eliminar este código fundador?'))return;const r=await sb.from('founder_codes').delete().eq('id',id);if(r.error)return toast(r.error.message);closeModal();await financeFetchAndRender('founders');toast('Código eliminado.')};

  function renderReports(c){
    const now=new Date(); const start=new Date(now.getFullYear(),now.getMonth(),1); const startIso=start.toISOString().slice(0,10); const p=window.__finance.payments.filter(x=>x.status==='approved'); const e=window.__finance.expenses;
    const income=p.filter(x=>(x.payment_date||x.created_at?.slice(0,10))>=startIso).reduce((s,x)=>s+Number(x.amount||0),0); const expense=e.filter(x=>(x.expense_date||'')>=startIso).reduce((s,x)=>s+Number(x.amount||0),0); const active=window.__finance.memberships.filter(x=>x.status==='active'&&x.end_date>=isoDate()).length; const founder=window.__finance.memberships.filter(x=>x.membership_plans?.is_founder_plan&&x.status==='active').length;
    const byPlan={}; p.filter(x=>(x.payment_date||x.created_at?.slice(0,10))>=startIso).forEach(x=>{const k=x.membership_plans?.name||x.concept||'Otros';byPlan[k]=(byPlan[k]||0)+Number(x.amount||0)});const max=Math.max(1,...Object.values(byPlan));
    c.innerHTML=`${financeHeader('reports')}<div class="fin-toolbar"><div class="muted">Resumen del mes actual · ${start.toLocaleDateString('es-MX',{month:'long',year:'numeric'})}</div><div class="fin-actions"><button class="btn out" onclick="expenseForm()">Registrar egreso</button></div></div><div class="fin-grid5"><div class="fin-kpi"><small>Ingresos</small><strong>${moneyF(income)}</strong></div><div class="fin-kpi"><small>Egresos</small><strong>${moneyF(expense)}</strong></div><div class="fin-kpi"><small>Balance</small><strong>${moneyF(income-expense)}</strong></div><div class="fin-kpi"><small>Membresías activas</small><strong>${active}</strong></div><div class="fin-kpi"><small>Fundadores activos</small><strong>${founder}</strong></div></div><div class="fin-chart"><div class="card"><div class="ey">Ingresos por concepto</div><h3>Este mes</h3>${Object.keys(byPlan).length?Object.entries(byPlan).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="fin-bar-row"><span>${escF(k)}</span><div class="fin-bar"><i style="width:${Math.max(8,v/max*100)}%"></i></div><b>${moneyF(v)}</b></div>`).join(''):'<div class="empty">Sin ingresos aprobados este mes.</div>'}</div><div class="card"><div class="ey">Egresos</div><h3>Últimos movimientos</h3>${e.length?e.slice(0,8).map(x=>`<div class="item"><div><b>${escF(x.concept)}</b><small>${dateF(x.expense_date)} · ${escF(x.category||'General')}</small></div><strong>${moneyF(x.amount)}</strong></div>`).join(''):'<div class="empty">Sin egresos registrados.</div>'}</div></div>`;
  }

  const oldAdminCoaches=adminCoaches;
  adminCoaches=async(c)=>{injectStyle();const r=await sb.from('coaches').select('*').order('is_active',{ascending:false}).order('name');const rows=r.data||[];window.__finance.coaches=rows;c.innerHTML=`<div class="hero"><div class="ey">Administración</div><h2>Coaches.</h2><p class="muted">Administra quién trabaja en ZONA 33 y qué coach aparece en la operación.</p><button class="btn red" onclick="coachFinanceForm()">Agregar coach</button></div><div class="grid grid2">${rows.map(x=>`<div class="card"><div style="display:flex;align-items:center;gap:12px"><div style="width:46px;height:46px;border-radius:50%;background:#f0f1f3;overflow:hidden;flex:none">${x.photo_url?`<img src="${escF(x.photo_url)}" style="width:100%;height:100%;object-fit:cover">`:''}</div><div><h3 style="margin:0">${escF(x.name)}</h3><div class="muted">${escF(x.specialty||'Coach')}</div></div></div><p class="muted">${escF(x.bio||'')}</p><span class="pill ${x.is_active?'ok':'bad'}">${x.is_active?'Activo':'Inactivo'}</span><div class="actions" style="margin-top:12px"><button class="btn out" onclick="coachFinanceForm('${x.id}')">Editar</button>${x.is_active?`<button class="btn danger" onclick="deleteCoachFinance('${x.id}')">Eliminar</button>`:`<button class="btn red" onclick="activateCoachFinance('${x.id}')">Reactivar</button>`}</div></div>`).join('')||'<div class="empty">No hay coaches.</div>'}</div>`};
  window.coachFinanceForm=id=>{const x=id?window.__finance.coaches.find(v=>v.id===id):null;modal(x?'Editar coach':'Agregar coach',`<form class="form" onsubmit="saveCoachFinance(event,'${id||''}')"><div class="row"><div class="field"><label>Nombre</label><input id="fcname" value="${escF(x?.name||'')}" required></div><div class="field"><label>Especialidad</label><input id="fcspec" value="${escF(x?.specialty||'')}"></div></div><div class="field"><label>Foto (URL)</label><input id="fcphoto" value="${escF(x?.photo_url||'')}" placeholder="https://…"></div><div class="field"><label>Bio</label><textarea id="fcbio">${escF(x?.bio||'')}</textarea></div><div class="actions"><button type="button" class="btn out" onclick="closeModal()">Cancelar</button><button class="btn red">Guardar</button></div></form>`) };
  window.saveCoachFinance=async(e,id)=>{e.preventDefault();const payload={name:fcname.value.trim(),specialty:fcspec.value.trim()||null,photo_url:fcphoto.value.trim()||null,bio:fcbio.value.trim()||null,updated_at:new Date().toISOString(),is_active:true};const r=id?await sb.from('coaches').update(payload).eq('id',id):await sb.from('coaches').insert(payload);if(r.error)return toast(r.error.message);closeModal();await refresh();toast('Coach guardado.');go('coaches')};
  window.deleteCoachFinance=async id=>{if(!confirm('¿Eliminar este coach de la operación? Se conservará el historial de sus clases.'))return;const r=await sb.from('coaches').update({is_active:false,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return toast(r.error.message);await refresh();toast('Coach eliminado de los activos.');go('coaches')};
  window.activateCoachFinance=async id=>{const r=await sb.from('coaches').update({is_active:true,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return toast(r.error.message);await refresh();toast('Coach reactivado.');go('coaches')};

  // Re-render the admin shell after app.js has booted so the new section structure is active.
  setTimeout(()=>{if(role==='admin'){renderShell();go('overview')}},0);
})();